const MONTHS = ["2026-01", "2026-02", "2026-03"];
const GENRES = ["キャラクター", "ミニチュア", "動物", "フィギュア", "おもしろ", "推し活"];
const PRICES = [200, 300, 400, 500, 600, 800, 1000, 1500];
const MAKERS = ["バンダイ", "タカラトミーアーツ", "ブシロードクリエイティブ", "キタンクラブ", "ケンエレファント", "SO-TA", "エスケイジャパン", "TOYS CABIN", "J.DREAM", "IP4", "ターリン・インターナショナル"];

const GACHA_DATA = [
  { id: 1, name: "ちいかわ ソフビフィギュア4", price: 400, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわのソフビフィギュアシリーズ第4弾", isNew: true, image: null },
  { id: 2, name: "THE!ガチャハンドル リターンズ", price: 400, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "ガチャハンドル型のユニークなグッズ", isNew: true, image: null },
  { id: 3, name: "夢グループ 動画名場面ポーチ", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "夢グループの動画名場面をプリントしたポーチ", isNew: true, image: null },
  { id: 4, name: "サンリオキャラクターズ リバーシブルぬいぐるみ いちごデザイン", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "いちごデザインのリバーシブルぬいぐるみ", isNew: true, image: null },
  { id: 5, name: "くら寿司 ミニチュア陶器コレクション", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "くら寿司の陶器をモチーフにしたミニチュア", isNew: true, image: null },
  { id: 6, name: "フロマージュ研究会", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "チーズをモチーフにしたミニチュアコレクション", isNew: true, image: null },
  { id: 7, name: "サンリオキャラクターズ ホイップクリームマスコット", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ホイップクリームモチーフのサンリオマスコット", isNew: true, image: null },
  { id: 8, name: "ぴかっと牛乳瓶ライト", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "牛乳瓶型のLEDライト", isNew: true, image: null },
  { id: 9, name: "ちいかわ おかお巾着②", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわの顔がプリントされた巾着袋", isNew: true, image: null },
  { id: 10, name: "サンリオキャラクターズ ダンボールウォッチ２", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ダンボール風デザインのサンリオ腕時計", isNew: true, image: null },
  { id: 11, name: "チケット当選お守り DAY３", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "チケット抽選の当選祈願お守り", isNew: true, image: null },
  { id: 12, name: "海物語 縦横ラバーマスコット vol.1", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "海物語キャラのラバーマスコット", isNew: true, image: null },
  { id: 13, name: "Lil ala mode ふりふりアクリルキーホルダー", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "エスケイジャパン", lineup: 5, description: "ふりふり揺れるアクリルキーホルダー", isNew: true, image: null },
  { id: 14, name: "ねこあし おちょこ", price: 500, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫の足型をかたどったおちょこ", isNew: true, image: null },
  { id: 15, name: "たまごっち カラフルキャンディチャーム", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "たまごっちのカラフルキャンディチャーム", isNew: true, image: null },
  { id: 16, name: "ならぶんです。銀牙 流れ星 銀", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "銀牙キャラを並べるシリーズ", isNew: true, image: null },
  { id: 17, name: "TOM and JERRY ライトマスコット3", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トムとジェリーのライト付きマスコット第3弾", isNew: true, image: null },
  { id: 18, name: "まちぼうけ けいおん！の場合", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "けいおん！コラボまちぼうけシリーズ", isNew: true, image: null },
  { id: 19, name: "ポケットモンスター おっきなお月さまライトマスコット", price: 600, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポケモンのお月さま型ライトマスコット", isNew: true, image: null },
  { id: 20, name: "ドラゴンボール めじるしアクセサリー3", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 6, description: "ドラゴンボールのめじるしアクセサリー第3弾", isNew: true, image: null },
  { id: 21, name: "めざましコラショ ミニチュアコレクション", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "めざましコラショのミニチュアグッズ", isNew: true, image: null },
  { id: 22, name: "Disney SERIES CREATED by MUS バッグコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニー×MUSのミニバッグコレクション", isNew: true, image: null },
  { id: 23, name: "タツノコプロ テレビ放映マスコット VOL.1", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "タツノコプロ作品のマスコット", isNew: true, image: null },
  { id: 24, name: "uni MITSUBISHI PENCIL ミニチュアチャーム3", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "uniペンのミニチュアチャーム第3弾", isNew: true, image: null },
  { id: 25, name: "本当に録音再生！ポータブルゲーム機マスコット", price: 500, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "録音再生機能付きゲーム機型マスコット", isNew: true, image: null },
  { id: 26, name: "ぴょす スクイーズ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ぴょすのスクイーズマスコット", isNew: true, image: null },
  { id: 27, name: "mofusand 豆皿コレクション", price: 400, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "もふさんどのキャラクター豆皿", isNew: true, image: null },
  { id: 28, name: "SPALDING BASKETBALL POUCH COLLECTION", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "スパルディングバスケットボール風ポーチ", isNew: true, image: null },
  { id: 29, name: "懐かしレトロ看板アクリルチャーム", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "レトロな看板モチーフのアクリルチャーム", isNew: true, image: null },
  { id: 30, name: "英単語ターゲット豆本コレクション", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "英単語ターゲット参考書の豆本ミニチュア", isNew: true, image: null },
  { id: 31, name: "ジェムリーズ ポケットモンスター12 Winter", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 6, description: "ポケモンのジェム型キーホルダー冬版", isNew: true, image: null },
  { id: 32, name: "スターダム ジュエルアクリルキーホルダー", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "スターダムプロレス選手のアクキー", isNew: true, image: null },
  { id: 33, name: "サンリオキャラクターズ エコバッグ ラテクマ", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ラテクマデザインのサンリオエコバッグ", isNew: true, image: null },
  { id: 34, name: "運命のコイン 恋愛編", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "恋愛運を占うコイン型グッズ", isNew: true, image: null },
  { id: 35, name: "まちぼうけGLAY", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "GLAYコラボまちぼうけシリーズ", isNew: true, image: null },
  { id: 36, name: "サンリオ リトルツインスターズ ぬいぐるみポシェット", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "キキララのぬいぐるみ型ポシェット", isNew: true, image: null },
  { id: 37, name: "ことりの葛まんじゅう うつろい", price: 200, releaseMonth: "2026-01", genre: "ミニチュア", maker: "SO-TA", lineup: 5, description: "葛まんじゅうモチーフのミニチュア", isNew: true, image: null },
  { id: 38, name: "EASTBOY ミニスクールバッグマスコット３", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "スクールバッグのミニチュアマスコット第3弾", isNew: true, image: null },
  { id: 39, name: "JILLbyJILLSTUART MINI FLUFFY TOTEBAG KEYHOLDER", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "JILLSTUART風ミニトートバッグ型キーホルダー", isNew: true, image: null },
  { id: 40, name: "ポムポムプリン マイカラーフィギュア", price: 300, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 6, description: "ポムポムプリンのカラフルフィギュア", isNew: true, image: null },
  { id: 41, name: "CoCo壱番屋 ミニチュアマスコットvol.2", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "CoCo壱メニューのミニチュアマスコット", isNew: true, image: null },
  { id: 42, name: "怒涛！チンチロマスコット2", price: 200, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "チンチロサイコロのマスコット第2弾", isNew: true, image: null },
  { id: 43, name: "サンリオ ポチャッコ ぬいぐるみボールチェーン", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポチャッコのぬいぐるみ型ボールチェーン", isNew: true, image: null },
  { id: 44, name: "野菜袋２", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "野菜パック袋のリアルミニチュア第2弾", isNew: true, image: null },
  { id: 45, name: "キン肉マン ドットフィギュアチャーム", price: 400, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 6, description: "キン肉マンのドット絵風フィギュアチャーム", isNew: true, image: null },
  { id: 46, name: "ヴィセ ミニチュアコレクション", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ヴィセコスメのミニチュアコレクション", isNew: true, image: null },
  { id: 47, name: "サンエックスユニバース バラエティーコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 6, description: "サンエックスキャラのバラエティーグッズ", isNew: true, image: null },
  { id: 48, name: "リラックマ のんびりネコ ふわふわポーチ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リラックマのふわふわポーチ", isNew: true, image: null },
  { id: 49, name: "はっぴ～ぬ！", price: 200, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "はっぴーな犬のマスコット", isNew: true, image: null },
  { id: 50, name: "ほっこり日和 猫", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫をモチーフにしたほっこりグッズ", isNew: true, image: null },
  { id: 51, name: "HG レジェンドライダーvol.5", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "仮面ライダーHGレジェンドライダー第5弾", isNew: true, image: null },
  { id: 52, name: "ちいかわ ライトクリップ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわのライト付きクリップ", isNew: true, image: null },
  { id: 53, name: "UNIVERSAL Music Push Button GODシリーズ", price: 500, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "音楽関連のプッシュボタン型グッズ", isNew: true, image: null },
  { id: 54, name: "ちいかわ×サンリオ なりきりフィギュア", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわがサンリオキャラに変身したフィギュア", isNew: true, image: null },
  { id: 55, name: "すみっコぐらし ほわっと光る！電球ライト2", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 6, description: "すみっコの電球型ライト第2弾", isNew: true, image: null },
  { id: 56, name: "リラックマ やわらかマスコット", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リラックマのやわらかマスコット", isNew: true, image: null },
  { id: 57, name: "モンチッチ もこもこスクエアポーチ くすみカラー", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "モンチッチのくすみカラーポーチ", isNew: true, image: null },
  { id: 58, name: "猫キャッチ", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫をキャッチするゲーム感覚グッズ", isNew: true, image: null },
  { id: 59, name: "ちいかわ×サンリオ レイヤーアクリルスタンド", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわ×サンリオのアクリルスタンド", isNew: true, image: null },
  { id: 60, name: "ないしょとーくFig. くまのプーさん", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "プーさんのないしょとーくフィギュア", isNew: true, image: null },
  { id: 61, name: "ハリー・ポッター ドビーいっぱいコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ハリポタのドビーコレクション", isNew: true, image: null },
  { id: 62, name: "サンリオキャラクターズ しっぽチャーム", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "サンリオキャラのしっぽ型チャーム", isNew: true, image: null },
  { id: 63, name: "なおにゃん スイング2", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "なおにゃんスイングマスコット第2弾", isNew: true, image: null },
  { id: 64, name: "HG ONE PIECE 01", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ワンピースHGフィギュア第1弾", isNew: true, image: null },
  { id: 65, name: "ミッフィー マスコットライトPart.3", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ミッフィーのライトマスコット第3弾", isNew: true, image: null },
  { id: 66, name: "リアル！呼び出しベル8", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "呼び出しベルをリアルに再現した第8弾", isNew: true, image: null },
  { id: 67, name: "サンリオ ステンドグラス風アクリルキーチェーン", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "ステンドグラス風サンリオキーチェーン", isNew: true, image: null },
  { id: 68, name: "リサとガスパール Fleurデザイン コレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リサガスのフルールデザインコレクション", isNew: true, image: null },
  { id: 69, name: "PINGU シリコンがまぐち", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ピングーのシリコン製がまぐち", isNew: true, image: null },
  { id: 70, name: "サンリオキャラクターズ お寿司キーチェーン", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのお寿司型キーチェーン", isNew: true, image: null },
  { id: 71, name: "タマ＆フレンズ BIG巾着&ポーチコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "タマ＆フレンズのBIG巾着とポーチ", isNew: true, image: null },
  { id: 72, name: "カードキャプターさくら くっつきマスコット", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "CCさくらのくっつきマスコット", isNew: true, image: null },
  { id: 73, name: "機動戦士ガンダム ならぶんです。ザク", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ガンダムザクのならぶんですシリーズ", isNew: true, image: null },
  { id: 74, name: "POWER KNUCKLE byTOUMA × KAMEN RIDER", price: 1000, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 4, description: "仮面ライダーコラボフィギュア", isNew: true, image: null },
  { id: 75, name: "サンリオ カプセルステッキ2", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのステッキ第2弾", isNew: true, image: null },
  { id: 76, name: "豆ガシャ本 超全集 仮面ライダーシリーズ", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 5, description: "仮面ライダーシリーズの豆本超全集", isNew: true, image: null },
  { id: 77, name: "それいけ！アンパンマン ポップンハウス6", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "アンパンマンのポップンハウス第6弾", isNew: true, image: null },
  { id: 78, name: "MINECRAFT ならぶんです。7", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "マイクラのならぶんです第7弾", isNew: true, image: null },
  { id: 79, name: "銀魂 BIGソフビコレクション", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "銀魂のBIGサイズソフビフィギュア", isNew: true, image: null },
  { id: 80, name: "アンパンマン てころがしわくわくカー！4", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "アンパンマンの転がして遊べるカー第4弾", isNew: true, image: null },
  { id: 81, name: "まちぼうけ パンダの場合", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "ブシロードクリエイティブ", lineup: 5, description: "パンダのまちぼうけシリーズ", isNew: true, image: null },
  { id: 82, name: "ポケモン りらくっしょんマスコット party", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "ポケモンのリラックスマスコット", isNew: true, image: null },
  { id: 83, name: "サンリオキャラクターズ Chocolate Doll", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "サンリオキャラのチョコレートドール", isNew: true, image: null },
  { id: 84, name: "機動戦士ガンダム MOBILE SUIT ENSEMBLE 30", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ガンダムMSアンサンブル第30弾", isNew: true, image: null },
  { id: 85, name: "nepia ミニチュアチャーム", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ネピアティッシュのミニチュアチャーム", isNew: true, image: null },
  { id: 86, name: "タカセ洋菓子 ミニチュアチャーム", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "タカセ洋菓子のミニチュアチャーム", isNew: true, image: null },
  { id: 87, name: "MOOMIN もふもふポーシェット", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンのもふもふポーシェット", isNew: true, image: null },
  { id: 88, name: "サンリオ もふもふポーシェット2", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのもふもふポーシェット第2弾", isNew: true, image: null },
  { id: 89, name: "サンリオ きらっととんでいけしゃぼん玉", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのしゃぼん玉グッズ", isNew: true, image: null },
  { id: 90, name: "日清カップヌードル めじるしアクセサリー", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "カップヌードルのめじるしアクセサリー", isNew: true, image: null },
  { id: 91, name: "矢沢あい カプセルラバーマスコット", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "矢沢あい漫画キャラのラバーマスコット", isNew: true, image: null },
  { id: 92, name: "ソフビめじるしバンド サンリオ", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 5, description: "サンリオのソフビ風めじるしバンド", isNew: true, image: null },
  { id: 93, name: "capsule flockies ハヌル×サンリオ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "スタジオハヌルとサンリオのflockies", isNew: true, image: null },
  { id: 94, name: "たまごっち ブリスターパッケージコレクション", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "たまごっちパッケージのミニチュア", isNew: true, image: null },
  { id: 95, name: "赤ずきんチャチャ めじるしアクセサリー", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "赤ずきんチャチャのめじるしアクセサリー", isNew: true, image: null },
  { id: 96, name: "DOLLEL FIGURE COLLECTION3", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ドール型フィギュアコレクション第3弾", isNew: true, image: null },
  { id: 97, name: "妖怪手ぬぐい", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "妖怪をモチーフにした手ぬぐい", isNew: true, image: null },
  { id: 98, name: "Kabuto ミニチュアヘルメットキーホルダー", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "カブトのミニチュアヘルメットキーホルダー", isNew: true, image: null },
  { id: 99, name: "縁起物和柄巾着", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "縁起物和柄の巾着袋", isNew: true, image: null },
  { id: 100, name: "緊急レバーマスコット5", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "緊急レバーモチーフのマスコット第5弾", isNew: true, image: null },
  { id: 101, name: "ぶらさがりハムスター", price: 400, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "ぶら下がりハムスターのカプセルトイ", isNew: true, image: null },
  { id: 102, name: "ふくふくシマエナガ フロッキーソフビかふぇカラー", price: 300, releaseMonth: "2026-02", genre: "動物", maker: "バンダイ", lineup: 5, description: "シマエナガのフロッキーソフビ", isNew: true, image: null },
  { id: 103, name: "ころはむコロン ほおぶくろ巾着", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ころはむコロンのほお袋型巾着", isNew: true, image: null },
  { id: 104, name: "オニすけ アクリルスタンドフィギュア", price: 300, releaseMonth: "2026-02", genre: "フィギュア", maker: "SO-TA", lineup: 5, description: "オニすけのアクリルスタンド", isNew: true, image: null },
  { id: 105, name: "ポケモン30周年 メタルチャームマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポケモン30周年記念メタルチャーム", isNew: true, image: null },
  { id: 106, name: "セサミストリート フラットポーチ", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "セサミキャラのフラットポーチ", isNew: true, image: null },
  { id: 107, name: "ハローキティ 刺繍カスタムキーホルダー", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "キティの刺繍キーホルダー", isNew: true, image: null },
  { id: 108, name: "アオハルスイング", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "青春のスイングフィギュア", isNew: true, image: null },
  { id: 109, name: "サンリオ かおりつきフルーツ大福マスコット", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "香り付きフルーツ大福型マスコット", isNew: true, image: null },
  { id: 110, name: "うちの子かわいい！ドッグリュック第2弾", price: 500, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "犬型ミニリュック第2弾", isNew: true, image: null },
  { id: 111, name: "焼き芋袋2", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "焼き芋袋のミニチュア", isNew: true, image: null },
  { id: 112, name: "いたずらぐまのグルーミー ネックストラップ", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "グルーミーのネックストラップ", isNew: true, image: null },
  { id: 113, name: "かわいい ぬいぐるみ BIG シャチ", price: 500, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "大型シャチのぬいぐるみ", isNew: true, image: null },
  { id: 114, name: "柴犬根付３", price: 300, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "柴犬の根付コレクション第3弾", isNew: true, image: null },
  { id: 115, name: "きらめき☆バルーンフィギュア【推しの子】", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "【推しの子】のバルーンフィギュア", isNew: true, image: null },
  { id: 116, name: "ガンダムヘッド めじるしアクセサリー", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ガンダムヘッドのめじるしアクセサリー", isNew: true, image: null },
  { id: 117, name: "ワンピース ミニチュアチャーム", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "ONE PIECEウエハースのミニチュアチャーム", isNew: true, image: null },
  { id: 118, name: "ねこうさぎちゃん たれみみ", price: 400, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "ねこうさぎのたれ耳ぬいぐるみ", isNew: true, image: null },
  { id: 119, name: "葬送のフリーレン つまんでつなげてますこっと2", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "フリーレンのマスコット第2弾", isNew: true, image: null },
  { id: 120, name: "でかリボンヘアクリップ", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "大きなリボンヘアクリップ", isNew: true, image: null },
  { id: 121, name: "うちの子のけだまだま", price: 400, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "けだまのマスコット", isNew: true, image: null },
  { id: 122, name: "mofusand×日比谷花壇 スカーフチャーム", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "mofusand×日比谷花壇コラボチャーム", isNew: true, image: null },
  { id: 123, name: "ONE PIECE ワンピの実ミクロ チャーム", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ONE PIECE悪魔の実ミニチュアチャーム", isNew: true, image: null },
  { id: 124, name: "みんなのポチャッコ これくしょん", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポチャッコのコレクション", isNew: true, image: null },
  { id: 125, name: "文房具刺繍チャーム", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "文房具モチーフの刺繍チャーム", isNew: true, image: null },
  { id: 126, name: "スーパーダンガンロンパ2 まちぼうけ", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "ダンガンロンパ2まちぼうけ", isNew: true, image: null },
  { id: 127, name: "ダンボいっぱいコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニー・ダンボのマスコット", isNew: true, image: null },
  { id: 128, name: "着せ替え人形は恋をする Season2 キーホルダー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "着せ恋のラバーキーホルダー", isNew: true, image: null },
  { id: 129, name: "ポケモン トートバッグ＆ポーチvol.10", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ポケモンのミニトート＆ポーチ", isNew: true, image: null },
  { id: 130, name: "パンダの穴 ミニチュアスナイパー４", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "キタンクラブ", lineup: 5, description: "パンダの穴ミニチュア第4弾", isNew: true, image: null },
  { id: 131, name: "ミリオンゴッド BGMプッシュボタン", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "ミリオンゴッドのBGM再生ボタン", isNew: true, image: null },
  { id: 132, name: "サンリオ がまぐちキーホルダー", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオのがまぐち型キーホルダー", isNew: true, image: null },
  { id: 133, name: "The History Collection PlayStation", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "プレステの歴史ミニチュア", isNew: true, image: null },
  { id: 134, name: "mofusand いちごチョコにゃんマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "mofusandいちごチョコのマスコット", isNew: true, image: null },
  { id: 135, name: "パンどろぼう カプセルヘアクリップ", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "パンどろぼうのヘアクリップ", isNew: true, image: null },
  { id: 136, name: "サンリオ ふわわフロッキーマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオのふわわフロッキーマスコット", isNew: true, image: null },
  { id: 137, name: "ケアベア クリアマスコットチャーム2", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ケアベアのクリアチャーム第2弾", isNew: true, image: null },
  { id: 138, name: "ムーミン ぬいタオル", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンのぬいぐるみタオル", isNew: true, image: null },
  { id: 139, name: "手のひらネットワーク機器4", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ネットワーク機器のミニチュア第4弾", isNew: true, image: null },
  { id: 140, name: "サンエックス 巾着＆ポーチコレクション", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "エスケイジャパン", lineup: 5, description: "サンエックスの巾着＆ポーチ", isNew: true, image: null },
  { id: 141, name: "ティニピン バラエティーコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ティニピンのバラエティーコレクション", isNew: true, image: null },
  { id: 142, name: "モンチッチ キーチェーンバッグコレクション", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "モンチッチのミニバッグコレクション", isNew: true, image: null },
  { id: 143, name: "ドラえもん Funny Time!", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ドラえもんのファニータイム", isNew: true, image: null },
  { id: 144, name: "けろけろけろっぴ バラエティーコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "けろっぴのバラエティーコレクション", isNew: true, image: null },
  { id: 145, name: "MINECRAFT めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "マイクラのめじるしアクセサリー", isNew: true, image: null },
  { id: 146, name: "パンツウエストポーチ", price: 400, releaseMonth: "2026-02", genre: "おもしろ", maker: "ケンエレファント", lineup: 5, description: "パンツ型ウエストポーチ", isNew: true, image: null },
  { id: 147, name: "Honda CIVIC TYPE R コレクション", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "ホンダシビックType Rミニカー", isNew: true, image: null },
  { id: 148, name: "Canon ミニチュアカメラコレクション", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "キヤノンカメラのミニチュア", isNew: true, image: null },
  { id: 149, name: "HGドラゴンボール04 MAJIN BUU SAGA", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ドラゴンボールHG魔人ブウ編", isNew: true, image: null },
  { id: 150, name: "パンダコパンダ 前髪クリップ2", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "パンダコパンダのヘアクリップ第2弾", isNew: true, image: null },
  { id: 151, name: "ELECTRO GAME COLLECTION 4", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "電子ゲーム機ミニチュア第4弾", isNew: true, image: null },
  { id: 152, name: "ミッフィー パステルバラエティーコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ミッフィーのパステルコレクション", isNew: true, image: null },
  { id: 153, name: "Chiikawa Baby 巾着ポーチ", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわベイビーの巾着ポーチ", isNew: true, image: null },
  { id: 154, name: "ドラクエVII ミニアクリルブロック", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "DQ7のミニアクリルブロック", isNew: true, image: null },
  { id: 155, name: "リサとガスパール ライトマスコット", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リサガスのライトマスコット", isNew: true, image: null },
  { id: 156, name: "銀魂 吉原大炎上 めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "銀魂劇場版のめじるしアクセサリー", isNew: true, image: null },
  { id: 157, name: "HG スーパー戦隊シリーズ vol.2", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "スーパー戦隊HGフィギュア第2弾", isNew: true, image: null },
  { id: 158, name: "サンリオ カラフルカラビナチャーム", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオのカラビナチャーム", isNew: true, image: null },
  { id: 159, name: "クッピーラムネ めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "クッピーラムネのめじるし", isNew: true, image: null },
  { id: 160, name: "ペコちゃん めじるしアクセサリー2026", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ペコちゃんお菓子のめじるし", isNew: true, image: null },
  { id: 161, name: "サンリオ GRWMマスコットチャーム", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオGRWM風マスコットチャーム", isNew: true, image: null },
  { id: 162, name: "クレヨンしんちゃん めざましサウンド", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "しんちゃんのめざましサウンド", isNew: true, image: null },
  { id: 163, name: "名探偵コナン コナン隊 プラス", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "コナン隊のフィギュアコレクション", isNew: true, image: null },
  { id: 164, name: "パワフルプロ野球 サウンドロップ", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "パワプロのサウンドドロップ", isNew: true, image: null },
  { id: 165, name: "ガンダム 閃光のハサウェイ ラバーマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "閃ハサのラバーマスコット", isNew: true, image: null },
  { id: 166, name: "まちぼうけ NARUTO ラーメン一楽 第2弾", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "NARUTOまちぼうけ第2弾", isNew: true, image: null },
  { id: 167, name: "ヒロアカ おくるみますこっとチャーム", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ヒロアカのおくるみマスコット", isNew: true, image: null },
  { id: 168, name: "kitson ミニチュアバッグコレクション", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "TOYS CABIN", lineup: 5, description: "kitsonのミニチュアバッグ", isNew: true, image: null },
  { id: 169, name: "暗闘で光る！UMA めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "暗闇で光るUMAのめじるし", isNew: true, image: null },
  { id: 170, name: "EVA POCKET めじるしアクセサリー", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "エヴァのポケットめじるし", isNew: true, image: null },
  { id: 171, name: "BASTARD!! カプセルフィギュア", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "BASTARD!!のカプセルフィギュア", isNew: true, image: null },
  { id: 172, name: "豆ガシャ本 サンリオ プロフィール帳", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのプロフィール帳", isNew: true, image: null },
  { id: 173, name: "アンパンマン カシャカシャ！みえるよ！", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "アンパンマンのカシャカシャおもちゃ", isNew: true, image: null },
  { id: 174, name: "TOM and JERRY おやつチャーム", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "トムジェリのしぼりクッキーチャーム", isNew: true, image: null },
  { id: 175, name: "パワーパフ ガールズ きゃらまかろん", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "パワパフガールズのフィギュア", isNew: true, image: null },
  { id: 176, name: "おしゅしだよ めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "おしゅしだよのめじるし", isNew: true, image: null },
  { id: 177, name: "どこでもいっしょ まちぼうけ２", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "どこいっしょまちぼうけ第2弾", isNew: true, image: null },
  { id: 178, name: "まちぼうけ キン肉マン2", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "キン肉マンまちぼうけ第2弾", isNew: true, image: null },
  { id: 179, name: "ディズニー Twinkle ゴム", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニーのキラキラゴムアクセ", isNew: true, image: null },
  { id: 180, name: "NEW ERA MLB Cap MINIATURE SWING", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ターリン・インターナショナル", lineup: 5, description: "MLBキャップのミニチュアスイング", isNew: true, image: null },
  { id: 181, name: "おじゃる丸 めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "おじゃる丸のめじるし", isNew: true, image: null },
  { id: 182, name: "クレヨンしんちゃん ミニ貯金箱", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "しんちゃんのミニ貯金箱", isNew: true, image: null },
  { id: 183, name: "サムライ ミニチュアチャーム", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "サムライのミニチュアチャーム", isNew: true, image: null },
  { id: 184, name: "テレタビーズ おやすみライトマスコット", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "テレタビーズのライトマスコット", isNew: true, image: null },
  { id: 185, name: "チロルチョコ めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "チロルチョコのめじるし", isNew: true, image: null },
  { id: 186, name: "HUNTER×HUNTER すわらせ隊りある2", price: 800, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "H×Hすわらせフィギュア第2弾", isNew: true, image: null },
  { id: 187, name: "まちぼうけ 聖闘士星矢", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "聖闘士星矢まちぼうけ", isNew: true, image: null },
  { id: 188, name: "矢沢あい BIG METAL RING", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "J.DREAM", lineup: 5, description: "矢沢あいのビッグメタルリング", isNew: true, image: null },
  { id: 189, name: "トイ・ストーリー エイリアン だいすきフード", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トイストーリーエイリアンのフードマスコット", isNew: true, image: null },
  { id: 190, name: "魔法使いサリー ミニチュアチャーム", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "魔法使いサリーのミニチュア", isNew: true, image: null },
  { id: 191, name: "パペットスンスン コインケース", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "スンスンのコインケース", isNew: true, image: null },
  { id: 192, name: "よつばと！ こまどりフィギュア", price: 400, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "よつばと！のこまどりフィギュア", isNew: true, image: null },
  { id: 193, name: "ホイッピ＆ラッピ アクリルチャーム", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ホイッピ＆ラッピのアクリルチャーム", isNew: true, image: null },
  { id: 194, name: "MUZIKTIGER ヘアアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "IP4", lineup: 5, description: "MUZIKTIGERのヘアアクセサリー", isNew: true, image: null },
  { id: 195, name: "San-X フィギュアコレクション Vol.2", price: 300, releaseMonth: "2026-02", genre: "フィギュア", maker: "エスケイジャパン", lineup: 5, description: "サンエックスオールスターズフィギュア", isNew: true, image: null },
  { id: 196, name: "まちぼうけ ウルトラマンの場合", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "ウルトラマンまちぼうけ", isNew: true, image: null },
  { id: 197, name: "クレヨンしんちゃん ミラーコレクション", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "しんちゃんのミラーコレクション", isNew: true, image: null },
  { id: 198, name: "幽☆遊☆白書 めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "幽遊白書のめじるし", isNew: true, image: null },
  { id: 199, name: "コジコジ スイング", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "コジコジのスイングフィギュア", isNew: true, image: null },

  { id: 201, name: "はぴだんぶい キラキラも～っと☆おうえんフィギュア", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "はぴだんぶいの応援フィギュア", isNew: true, image: null },
  { id: 202, name: "推し×スシ 推スシ", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "推し活×寿司のコラボネタマスコット", isNew: true, image: null },
  { id: 203, name: "こっちむいてFig.その着せ替え人形は恋をする", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "その着せ替え人形は恋をするの着せ替えフィギュア", isNew: true, image: null },
  { id: 204, name: "MOOMINフロッキーフィギュアマスコット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンのふわふわフロッキーマスコット", isNew: true, image: null },
  { id: 205, name: "miffy すやすやフレンドFig.ぱすてる", price: 200, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ミッフィーのパステルカラーフィギュア", isNew: true, image: null },
  { id: 206, name: "カプセルプラレール きかんしゃトーマス", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トーマスのカプセルプラレール", isNew: true, image: null },
  { id: 207, name: "SANKYO激熱柄・激熱音プッシュボタンマスコット", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "パチンコの激熱柄＆音が楽しめるプッシュボタンマスコット", isNew: true, image: null },
  { id: 208, name: "ぷよぷよ マスコットめじるしチャーム", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ぷよぷよキャラのめじるしチャーム", isNew: true, image: null },
  { id: 209, name: "ちいかわ ラメアクリルキーホルダー5", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわのラメ入りアクリルキーホルダー", isNew: true, image: null },
  { id: 210, name: "CONVERSE SHOES COLLECTION めじるしアクセサリー", price: 400, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "コンバーススニーカーのミニチュアアクセサリー", isNew: true, image: null },
  { id: 211, name: "どっちも主役！ポメラニアン", price: 200, releaseMonth: "2026-03", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "ポメラニアンのキュートなマスコット", isNew: true, image: null },
  { id: 212, name: "チュッパチャプス ミニチュアコレクション Limited flavor2", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "チュッパチャプスの限定フレーバーミニチュア", isNew: true, image: null },
  { id: 213, name: "ホビーガチャ トヨタ GR Supra -COMPLATE EDITION-", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "トヨタGRスープラの完成品ミニカー", isNew: true, image: null },
  { id: 214, name: "どこでもいっしょ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "トロのめじるしアクセサリー", isNew: true, image: null },
  { id: 215, name: "本当に剥けちゃう！むにゅむにゅ！ふつ〜のバナナマスコット", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "皮が剥けるリアルなバナナマスコット", isNew: true, image: null },
  { id: 216, name: "ギャビーのドールハウス ザ・ムービー つながるラバーマスコット", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ギャビーのドールハウスキャラのつながるラバーマスコット", isNew: true, image: null },
  { id: 217, name: "EVERLAST ボクシンググローブコレクション", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "エバーラストのボクシンググローブミニチュア", isNew: true, image: null },
  { id: 218, name: "ミッフィー巾着コレクション", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ミッフィー柄の巾着バッグコレクション", isNew: true, image: null },
  { id: 219, name: "しなこ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "しなこのめじるしアクセサリー", isNew: true, image: null },
  { id: 220, name: "ヤマザキパン ミニチュアチャーム2", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ヤマザキパンのミニチュアチャーム", isNew: true, image: null },
  { id: 221, name: "ミートバッグ", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "お肉のバッグ型ユニークグッズ", isNew: true, image: null },
  { id: 222, name: "ふんばり～ぬ3", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "キタンクラブ", lineup: 5, description: "ふんばる犬のユニークマスコット第3弾", isNew: true, image: null },
  { id: 223, name: "BRANDALISEDアクリルキーチェーン", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "ブランド商品のアクリルキーチェーン", isNew: true, image: null },
  { id: 224, name: "パウ・パトロール パウっとつながるマスコット2", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "パウパトロールのつながるマスコット第2弾", isNew: true, image: null },
  { id: 225, name: "B.LEAGUE マスコット めじるしアクセサリー2", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "Bリーグ各チームマスコットのめじるしアクセサリー", isNew: true, image: null },
  { id: 226, name: "運命のコイン4", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "運命を占うコインコレクション第4弾", isNew: true, image: null },
  { id: 227, name: "Calbeeじゃがりこ おみくじマスコット", price: 500, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "じゃがりこパッケージのおみくじマスコット", isNew: true, image: null },
  { id: 228, name: "ズートピア ブリスターチャームコレクション", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ズートピアキャラのブリスターチャーム", isNew: true, image: null },
  { id: 229, name: "トゥイーティーなりきりスイング", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トゥイーティーのきぐるみスイングマスコット", isNew: true, image: null },
  { id: 230, name: "AIP森口修の猫フィギュアマスコット3", price: 500, releaseMonth: "2026-03", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "森口修デザインの猫フィギュアマスコット", isNew: true, image: null },
  { id: 231, name: "コジコジ Capsule Flockies", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "コジコジのcapsule flockies", isNew: true, image: null },
  { id: 232, name: "機動戦士ガンダム ならぶんです。ハロ ビッグサイズ", price: 800, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ガンダムのハロが並ぶビッグサイズフィギュア", isNew: true, image: null },
  { id: 233, name: "MOOMIN マスコットチャーム～funny style～", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンの面白いスタイルのマスコットチャーム", isNew: true, image: null },
  { id: 234, name: "MINECRAFT ライトマスコット3", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "マインクラフトの光るライトマスコット第3弾", isNew: true, image: null },
  { id: 235, name: "capsule flockies Winnie the Pooh", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "くまのプーさんのcapsule flockies", isNew: true, image: null },
  { id: 236, name: "PEANUTS パッケージミニチュアコレクション クラシックver.", price: 400, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "スヌーピーパッケージのミニチュアコレクション", isNew: true, image: null },
  { id: 237, name: "From TV animation ONE PIECE ワンピの実 GRAND CAPSULE Vol.02", price: 1500, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ONE PIECE悪魔の実のグランドカプセル第2弾", isNew: true, image: null },
  { id: 238, name: "ウルトラマン MINI ULTRA ART めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ウルトラマンのミニウルトラアートめじるしアクセサリー", isNew: true, image: null },
  { id: 239, name: "プロ野球マスコット めじるしアクセサリー", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "プロ野球各球団マスコットのめじるしアクセサリー", isNew: true, image: null },
  { id: 240, name: "ポケットモンスター 旅立ちの3匹アクリルスイング", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "旅立ちの3匹のアクリルスイングチャーム", isNew: true, image: null },
  { id: 241, name: "PEANUTS ビスケットミニチュアチャーム", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "スヌーピー柄ビスケットのミニチュアチャーム", isNew: true, image: null },
  { id: 242, name: "サンリオキャラクターズ シュウマイ", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのシュウマイ型マスコット", isNew: true, image: null },
  { id: 243, name: "映画ドラえもん メモリアルウォータードームコレクション", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "映画ドラえもんの水中ドーム型コレクション", isNew: true, image: null },
  { id: 244, name: "妖怪ウォッチ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "妖怪ウォッチキャラのめじるしアクセサリー", isNew: true, image: null },
  { id: 245, name: "パンダの穴 PET HOOD", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "キタンクラブ", lineup: 5, description: "パンダの穴のペット用フード", isNew: true, image: null },
  { id: 246, name: "内藤ルネ ルネパンダ アクリルめじるしチャーム", price: 300, releaseMonth: "2026-03", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "内藤ルネのルネパンダアクリルチャーム", isNew: true, image: null },
  { id: 247, name: "モンチッチ めじるしアクセサリー2", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "モンチッチのめじるしアクセサリー第2弾", isNew: true, image: null },
  { id: 248, name: "Studio Haneul×Sanrio characters ふわふわフロッキーマスコット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "スタジオハヌール×サンリオのふわふわフロッキー", isNew: true, image: null },
  { id: 249, name: "ジョジョの奇妙な冒険 まちぼうけ スターダストクルセイダース01", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "ジョジョ第三部のまちぼうけフィギュア", isNew: true, image: null },
  { id: 250, name: "＠CTION RIDE 仮面ライダー5", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "仮面ライダーのアクションライドフィギュア第5弾", isNew: true, image: null },
  { id: 251, name: "レトロメモリーズうわばき入れ風カードポーチ", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "懐かしいうわばき入れデザインのカードポーチ", isNew: true, image: null },
  { id: 252, name: "パワーパフガールズ きぐるみスイング", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "パワーパフガールズのきぐるみスイングマスコット", isNew: true, image: null },
  { id: 253, name: "ポケモン30周年 メタルチャームマスコット", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポケモン30周年記念メタルチャーム", isNew: true, image: null },
  { id: 254, name: "機動戦士ガンダム ガシャポン戦士ZERO 01", price: 300, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ガンダムガシャポン戦士ZEROシリーズ", isNew: true, image: null },
  { id: 255, name: "葬送のフリーレン ねむらせ隊", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "葬送のフリーレンのねむらせ隊フィギュア", isNew: true, image: null },
  { id: 256, name: "ドラえもん つながリングチャーム", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ドラえもんのつながるリングチャーム", isNew: true, image: null },
  { id: 257, name: "capsule flockies たまごっち", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "たまごっちのcapsule flockies", isNew: true, image: null },
  { id: 258, name: "光るポメラニアン", price: 500, releaseMonth: "2026-03", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "光るポメラニアンマスコット", isNew: true, image: null },
  { id: 259, name: "3年Z組銀八先生 まちぼうけ", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "銀八先生のまちぼうけフィギュア", isNew: true, image: null },
  { id: 260, name: "キン肉マン ダイキャストキンケシ12", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "キン肉マンのダイキャストキンケシ第12弾", isNew: true, image: null },
  { id: 261, name: "名探偵コナン めじるしアクセサリー3", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "名探偵コナンのめじるしアクセサリー第3弾", isNew: true, image: null },
  { id: 262, name: "ちびまる子ちゃん ぬいぐるみ巾着3", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ちびまる子ちゃんのぬいぐるみ巾着第3弾", isNew: true, image: null },
  { id: 263, name: "東京メトロ サウンドロップ", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "東京メトロの音が鳴るサウンドロップ", isNew: true, image: null },
  { id: 264, name: "サンリオキャラクターズ ミニチャーム付きリボンタッセルPart.2", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのリボンタッセル第2弾", isNew: true, image: null },
  { id: 265, name: "ふくふくシマエナガ 文庫本用巾着トート", price: 400, releaseMonth: "2026-03", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "シマエナガ柄の文庫本用巾着トート", isNew: true, image: null },
  { id: 266, name: "サンリオキャラクターズ ワンダフルワールドバッグコレクション", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオのワンダフルワールドバッグ", isNew: true, image: null },
  { id: 267, name: "DARTSLIVE サウンドミニチュアコレクション2", price: 500, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "ダーツのサウンドミニチュア第2弾", isNew: true, image: null },
  { id: 268, name: "つくし坊や はさむんです。でらっくす", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "つくし坊やのはさむクリップでらっくす", isNew: true, image: null },
  { id: 269, name: "サンリオキャラクターズ いつも一緒フレームキーチェーン Part.1", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのフレームキーチェーン", isNew: true, image: null },
  { id: 270, name: "ダッシュ無用！ピンポン PREMIUM2", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "ピンポン球のプレミアムマスコット第2弾", isNew: true, image: null },
  { id: 271, name: "サンリオキャラクターズ クッキー缶チャーム", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのクッキー缶型チャーム", isNew: true, image: null },
  { id: 272, name: "まちぼうけ ドラゴンボール3", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "ドラゴンボールのまちぼうけフィギュア第3弾", isNew: true, image: null },
  { id: 273, name: "ハローキティ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ハローキティのめじるしアクセサリー", isNew: true, image: null },
  { id: 274, name: "毛玉ビーム", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "猫の毛玉ビーム発射ユニークグッズ", isNew: true, image: null },
  { id: 275, name: "すみっコぐらし 喫茶すみっコでいちごフェア マスコットライト2", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "すみっコぐらしのマスコットライト第2弾", isNew: true, image: null },
  { id: 276, name: "サンリオ ハンギョドン ぬいぐるみボールチェーン2", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ハンギョドンのぬいぐるみボールチェーン", isNew: true, image: null },
  { id: 277, name: "ピクサーキャラクター ファッションリング ロイヤルクリア", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ピクサーキャラのファッションリング", isNew: true, image: null },
  { id: 278, name: "戦車のタンコ", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "戦車のタンコキャラクターグッズ", isNew: true, image: null },
  { id: 279, name: "東京ばな奈 スクイーズマスコット", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "東京ばな奈のスクイーズマスコット", isNew: true, image: null },
  { id: 280, name: "San-Xオールスターズ BOXティッシュカバー", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンエックスキャラのティッシュボックスカバー", isNew: true, image: null },
  { id: 281, name: "肩ズンFig. MOOMIN Part4", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンの肩乗りフィギュア第4弾", isNew: true, image: null },
  { id: 282, name: "PEANUTS もふもふポーシェット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "スヌーピーのもふもふポーチ", isNew: true, image: null },
  { id: 283, name: "マイメロディ ぬいぐるみチャーム", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "マイメロディのぬいぐるみチャーム", isNew: true, image: null },
  { id: 284, name: "転生したらスライムだった件 リムルさまがいっぱいフィギュア", price: 300, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "転スラのリムルさまフィギュア", isNew: true, image: null },
  { id: 285, name: "サンリオ ウサハナ ぬいぐるみポシェット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ウサハナのぬいぐるみポーチ", isNew: true, image: null },
  { id: 286, name: "ドラネッツ3飛竜型", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ドラネッツの飛竜型フィギュア", isNew: true, image: null },
  { id: 287, name: "サンリオ ハローキティ トートバッグ", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ハローキティのトートバッグ", isNew: true, image: null },
  { id: 288, name: "うちのポケモンマスコット しらんぷり", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "うちのポケモンのしらんぷりマスコット", isNew: true, image: null },
  { id: 289, name: "サンリオキャラクターズ おきあがりマスコット4", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのおきあがりこぼし第4弾", isNew: true, image: null },
  { id: 290, name: "ポップンユニコーンぷちぐるみ", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポップンユニコーンのぷちぬいぐるみ", isNew: true, image: null },
  { id: 291, name: "メダリスト スピンアクリルスタンド", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "メダリストのスピンアクリルスタンド", isNew: true, image: null },
  { id: 292, name: "ディズニープリンセス まみれるFig.", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニープリンセスのまみれるフィギュア", isNew: true, image: null },
  { id: 293, name: "初音ミク すってんころりんフィギュア2", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "初音ミクの転倒フィギュア第2弾", isNew: true, image: null },
  { id: 294, name: "おそ松さん ぺたっとねじまきますこっと", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "おそ松さんのネジマスコット", isNew: true, image: null },
  { id: 295, name: "ハローキティ 喜怒★哀楽!?ファションリングコレクション", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "キティの喜怒哀楽ファッションリング", isNew: true, image: null },
  { id: 296, name: "カーラーついてますよ。ヘアクリップ", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "カーラー付きのヘアクリップ", isNew: true, image: null },
  { id: 297, name: "サモエドくん ふわふわぽん", price: 300, releaseMonth: "2026-03", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "サモエドくんのふわふわマスコット", isNew: true, image: null },
  { id: 298, name: "ずりおちピンチ！にゃんこフック", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "滑り落ち防止のにゃんこフック", isNew: true, image: null },
  { id: 299, name: "サンリオキャラクターズ さくらマジックアクリルカラビナ", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラの桜マジックアクリルカラビナ", isNew: true, image: null },
  { id: 300, name: "サンリオキャラクターズ ふわふわパンマスコット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのふわふわパンマスコット", isNew: true, image: null }

];
