const GACHA_DATA = [
  // ── 2026年3月 ──
  {
    id: 1,
    name: "すみっコぐらし カプセルフィギュア vol.8",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 400,
    releaseMonth: "2026-03",
    image: "images/01_sumikko.jpg",
    description: "すみっコたちの新しいポーズが勢揃い！全5種。",
    lineup: 5,
    isNew: true,
  },
  {
    id: 2,
    name: "ミニチュア文房具マスコット",
    maker: "タカラトミーアーツ",
    genre: "ミニチュア",
    price: 300,
    releaseMonth: "2026-03",
    image: "images/02_bungu.jpg",
    description: "リアルな文房具がミニチュアに！全6種。",
    lineup: 6,
    isNew: true,
  },
  {
    id: 3,
    name: "猫のかぶりもの 第15弾",
    maker: "キタンクラブ",
    genre: "動物",
    price: 400,
    releaseMonth: "2026-03",
    image: "images/03_neko.jpg",
    description: "大人気シリーズ最新弾！春の和菓子編。全6種。",
    lineup: 6,
    isNew: true,
  },
  {
    id: 4,
    name: "ポケットモンスター テラスタルフィギュア",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 500,
    releaseMonth: "2026-03",
    image: "images/04_pokemon.jpg",
    description: "テラスタル姿のポケモンたちがガチャに登場！全4種。",
    lineup: 4,
    isNew: true,
  },
  {
    id: 5,
    name: "ミニチュアキッチン家電コレクション",
    maker: "エポック",
    genre: "ミニチュア",
    price: 300,
    releaseMonth: "2026-03",
    image: "images/05_kitchen.jpg",
    description: "精巧なキッチン家電のミニチュア。全5種。",
    lineup: 5,
    isNew: true,
  },
  {
    id: 6,
    name: "推し活グッズ ハートアクスタケース",
    maker: "ブシロードクリエイティブ",
    genre: "推し活",
    price: 400,
    releaseMonth: "2026-03",
    image: "images/06_oshikatsu.jpg",
    description: "推しのアクスタを可愛く飾れるケース！全5色。",
    lineup: 5,
    isNew: true,
  },
  // ── 2026年4月 ──
  {
    id: 7,
    name: "サンリオキャラクターズ お花見マスコット",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 400,
    releaseMonth: "2026-04",
    image: "images/07_sanrio.jpg",
    description: "桜の季節にぴったり！お花見ポーズのサンリオキャラ。全6種。",
    lineup: 6,
    isNew: false,
  },
  {
    id: 8,
    name: "リアルフード ラーメン屋台編",
    maker: "タカラトミーアーツ",
    genre: "ミニチュア",
    price: 500,
    releaseMonth: "2026-04",
    image: "images/08_ramen.jpg",
    description: "屋台ラーメンをリアルに再現！全5種。",
    lineup: 5,
    isNew: false,
  },
  {
    id: 9,
    name: "虫カプセル 甲虫コレクション",
    maker: "バンダイ",
    genre: "動物",
    price: 500,
    releaseMonth: "2026-04",
    image: "images/09_mushi.jpg",
    description: "精巧な甲虫フィギュア。全4種。",
    lineup: 4,
    isNew: false,
  },
  {
    id: 10,
    name: "呪術廻戦 デフォルメフィギュア vol.5",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 400,
    releaseMonth: "2026-04",
    image: "images/10_jujutsu.jpg",
    description: "渋谷事変の名シーンをデフォルメ化！全5種。",
    lineup: 5,
    isNew: false,
  },
  {
    id: 11,
    name: "ミニチュア和菓子コレクション 春編",
    maker: "エポック",
    genre: "ミニチュア",
    price: 300,
    releaseMonth: "2026-04",
    image: "images/11_wagashi.jpg",
    description: "美しい和菓子をミニチュア化。全6種。",
    lineup: 6,
    isNew: false,
  },
  {
    id: 12,
    name: "推しぬい着せ替え パステルコーデ",
    maker: "ブシロードクリエイティブ",
    genre: "推し活",
    price: 300,
    releaseMonth: "2026-04",
    image: "images/12_oshinui.jpg",
    description: "推しぬいの着せ替えパステルカラー衣装！全6種。",
    lineup: 6,
    isNew: false,
  },
  // ── 2026年5月 ──
  {
    id: 13,
    name: "ちいかわ なんか小さくてかわいいフィギュア vol.4",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 400,
    releaseMonth: "2026-05",
    image: "images/13_chiikawa.jpg",
    description: "ちいかわワールドの仲間たちが集合！全5種。",
    lineup: 5,
    isNew: false,
  },
  {
    id: 14,
    name: "ミニチュア純喫茶コレクション",
    maker: "ケンエレファント",
    genre: "ミニチュア",
    price: 400,
    releaseMonth: "2026-05",
    image: "images/14_kissaten.jpg",
    description: "レトロな純喫茶メニューを完全再現！全6種。",
    lineup: 6,
    isNew: false,
  },
  {
    id: 15,
    name: "柴犬の日常 第5弾",
    maker: "キタンクラブ",
    genre: "動物",
    price: 300,
    releaseMonth: "2026-05",
    image: "images/15_shiba.jpg",
    description: "柴犬のゆるい日常シリーズ第5弾！全6種。",
    lineup: 6,
    isNew: false,
  },
  {
    id: 16,
    name: "ワンピース ギア5フィギュアコレクション",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 500,
    releaseMonth: "2026-05",
    image: "images/16_onepiece.jpg",
    description: "ルフィのギア5変形フィギュア！全4種。",
    lineup: 4,
    isNew: false,
  },
  {
    id: 17,
    name: "ミニチュア レトロ家電コレクション",
    maker: "タカラトミーアーツ",
    genre: "ミニチュア",
    price: 300,
    releaseMonth: "2026-05",
    image: "images/17_retro.jpg",
    description: "昭和レトロな家電がミニチュアに！全5種。",
    lineup: 5,
    isNew: false,
  },
  {
    id: 18,
    name: "推し活 ネームプレートホルダー",
    maker: "ブシロードクリエイティブ",
    genre: "推し活",
    price: 400,
    releaseMonth: "2026-05",
    image: "images/18_oshiname.jpg",
    description: "推しの名前を入れられるホルダー！全5色。",
    lineup: 5,
    isNew: false,
  },
  // ── 2026年6月 ──
  {
    id: 19,
    name: "SPY×FAMILY デフォルメフィギュア vol.3",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 400,
    releaseMonth: "2026-06",
    image: "images/19_spy.jpg",
    description: "フォージャー家の日常シーンを再現！全5種。",
    lineup: 5,
    isNew: false,
  },
  {
    id: 20,
    name: "ミニチュア夏祭り屋台コレクション",
    maker: "エポック",
    genre: "ミニチュア",
    price: 400,
    releaseMonth: "2026-06",
    image: "images/20_matsuri.jpg",
    description: "夏祭りの屋台をミニチュア化！全6種。",
    lineup: 6,
    isNew: false,
  },
  {
    id: 21,
    name: "カエルのガラス細工コレクション",
    maker: "キタンクラブ",
    genre: "動物",
    price: 500,
    releaseMonth: "2026-06",
    image: "images/21_kaeru.jpg",
    description: "繊細なガラス細工のカエルたち。全5種。",
    lineup: 5,
    isNew: false,
  },
  {
    id: 22,
    name: "ドラゴンボール ミニフィギュアコレクション",
    maker: "バンダイ",
    genre: "キャラクター",
    price: 500,
    releaseMonth: "2026-06",
    image: "images/22_dragonball.jpg",
    description: "名場面を再現したミニフィギュア！全4種。",
    lineup: 4,
    isNew: false,
  },
  {
    id: 23,
    name: "ミニチュア昭和レトロ看板コレクション",
    maker: "ケンエレファント",
    genre: "ミニチュア",
    price: 300,
    releaseMonth: "2026-06",
    image: "images/23_kanban.jpg",
    description: "懐かしの看板がミニチュアに！全6種。",
    lineup: 6,
    isNew: false,
  },
  {
    id: 24,
    name: "推し活 デコシールメーカー",
    maker: "タカラトミーアーツ",
    genre: "推し活",
    price: 300,
    releaseMonth: "2026-06",
    image: "images/24_decoseal.jpg",
    description: "推し活デコに使えるシールセット！全5種。",
    lineup: 5,
    isNew: false,
  },
];

const GENRES = [...new Set(GACHA_DATA.map((g) => g.genre))].sort();
const MAKERS = [...new Set(GACHA_DATA.map((g) => g.maker))].sort();
const PRICES = [...new Set(GACHA_DATA.map((g) => g.price))].sort((a, b) => a - b);
const MONTHS = [...new Set(GACHA_DATA.map((g) => g.releaseMonth))].sort();
