const MONTHS = ["2026-01", "2026-02", "2026-03", "2026-04", "2026-05", "2026-06"];
const GENRES = ["キャラクター", "ミニチュア", "動物", "フィギュア", "おもしろ", "推し活"];
const PRICES = [200, 300, 400, 500, 600, 800, 1000, 1500];
const MAKERS = ["バンダイ", "タカラトミーアーツ", "IP4", "キタンクラブ", "ブシロードクリエイティブ", "ケンエレファント", "J.DREAM", "TOYS CABIN", "夢屋", "ピーナッツクラブ", "ターリン・インターナショナル", "アミューズ", "SO-TA", "パレード", "ブシロード", "ケーツーステーション", "ウルトラニュープランニング", "Qualia", "コトフル", "エスケイジャパン", "ディーアイエス", "ブライトリンク", "いきもん", "エール", "トーシン", "レインボー", "トイズスピリッツ"];

const GACHA_DATA = [
  { id: 1, name: "ちいかわ ソフビフィギュア4", price: 400, releaseMonth: "2026-01", genre: "フィギュア", maker: "パレード", lineup: 5, description: "ちいかわのソフビフィギュアシリーズ第4弾", isNew: true, image: "images/001.jpg" },
  { id: 2, name: "THE!ガチャハンドル リターンズ", price: 400, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "ガチャハンドル型のユニークなグッズ", isNew: true, image: "images/002.jpg" },
  { id: 3, name: "夢グループ 動画名場面ポーチ", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "ピーナッツクラブ", lineup: 5, description: "夢グループの動画名場面をプリントしたポーチ", isNew: true, image: "images/003.jpg" },
  { id: 4, name: "サンリオキャラクターズ リバーシブルぬいぐるみ いちごデザイン", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "いちごデザインのリバーシブルぬいぐるみ", isNew: true, image: "images/004.jpg" },
  { id: 5, name: "くら寿司 ミニチュア陶器コレクション", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "くら寿司の陶器をモチーフにしたミニチュア", isNew: true, image: "images/005.jpg" },
  { id: 6, name: "フロマージュ研究会", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "チーズをモチーフにしたミニチュアコレクション", isNew: true, image: "images/006.jpg" },
  { id: 7, name: "サンリオキャラクターズ ホイップクリームマスコット", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ホイップクリームモチーフのサンリオマスコット", isNew: true, image: "images/007.jpg" },
  { id: 8, name: "ぴかっと牛乳瓶ライト", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "牛乳瓶型のLEDライト", isNew: true, image: "images/008.jpg" },
  { id: 9, name: "ちいかわ おかお巾着②", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわの顔がプリントされた巾着袋", isNew: true, image: "images/009.jpg" },
  { id: 10, name: "サンリオキャラクターズ ダンボールウォッチ２", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ダンボール風デザインのサンリオ腕時計", isNew: true, image: "images/010.jpg" },
  { id: 11, name: "チケット当選お守り DAY３", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "チケット抽選の当選祈願お守り", isNew: true, image: "images/011.jpg" },
  { id: 12, name: "海物語 縦横ラバーマスコット vol.1", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "海物語キャラのラバーマスコット", isNew: true, image: "images/012.jpg" },
  { id: 13, name: "Lil ala mode ふりふりアクリルキーホルダー", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "エスケイジャパン", lineup: 5, description: "ふりふり揺れるアクリルキーホルダー", isNew: true, image: "images/013.jpg" },
  { id: 14, name: "ねこあし おちょこ", price: 500, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫の足型をかたどったおちょこ", isNew: true, image: "images/014.jpg" },
  { id: 15, name: "たまごっち カラフルキャンディチャーム", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "たまごっちのカラフルキャンディチャーム", isNew: true, image: "images/015.jpg" },
  { id: 16, name: "ならぶんです。銀牙 流れ星 銀", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "銀牙キャラを並べるシリーズ", isNew: true, image: "images/016.jpg" },
  { id: 17, name: "TOM and JERRY ライトマスコット3", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トムとジェリーのライト付きマスコット第3弾", isNew: true, image: "images/017.jpg" },
  { id: 18, name: "まちぼうけ けいおん！の場合", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "けいおん！コラボまちぼうけシリーズ", isNew: true, image: "images/018.jpg" },
  { id: 19, name: "ポケットモンスター おっきなお月さまライトマスコット", price: 600, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポケモンのお月さま型ライトマスコット", isNew: true, image: "images/019.jpg" },
  { id: 20, name: "ドラゴンボール めじるしアクセサリー3", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 6, description: "ドラゴンボールのめじるしアクセサリー第3弾", isNew: true, image: "images/020.jpg" },
  { id: 21, name: "めざましコラショ ミニチュアコレクション", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "めざましコラショのミニチュアグッズ", isNew: true, image: "images/021.jpg" },
  { id: 22, name: "Disney SERIES CREATED by MUS バッグコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニー×MUSのミニバッグコレクション", isNew: true, image: "images/022.jpg" },
  { id: 23, name: "タツノコプロ テレビ放映マスコット VOL.1", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "タツノコプロ作品のマスコット", isNew: true, image: "images/023.jpg" },
  { id: 24, name: "uni MITSUBISHI PENCIL ミニチュアチャーム3", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "uniペンのミニチュアチャーム第3弾", isNew: true, image: "images/024.jpg" },
  { id: 25, name: "本当に録音再生！ポータブルゲーム機マスコット", price: 500, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "録音再生機能付きゲーム機型マスコット", isNew: true, image: "images/025.jpg" },
  { id: 26, name: "ぴょす スクイーズ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ぴょすのスクイーズマスコット", isNew: true, image: "images/026.jpg" },
  { id: 27, name: "mofusand 豆皿コレクション", price: 400, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "もふさんどのキャラクター豆皿", isNew: true, image: "images/027.jpg" },
  { id: 28, name: "SPALDING BASKETBALL POUCH COLLECTION", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "スパルディングバスケットボール風ポーチ", isNew: true, image: "images/028.jpg" },
  { id: 29, name: "懐かしレトロ看板アクリルチャーム", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "レトロな看板モチーフのアクリルチャーム", isNew: true, image: "images/029.jpg" },
  { id: 30, name: "英単語ターゲット豆本コレクション", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "英単語ターゲット参考書の豆本ミニチュア", isNew: true, image: "images/030.jpg" },
  { id: 31, name: "ジェムリーズ ポケットモンスター12 Winter", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "ポケモンのジェム型キーホルダー冬版", isNew: true, image: "images/031.jpg" },
  { id: 32, name: "スターダム ジュエルアクリルキーホルダー", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "スターダムプロレス選手のアクキー", isNew: true, image: "images/032.jpg" },
  { id: 33, name: "サンリオキャラクターズ エコバッグ ラテクマ", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ラテクマデザインのサンリオエコバッグ", isNew: true, image: "images/033.jpg" },
  { id: 34, name: "運命のコイン 恋愛編", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "ブシロードクリエイティブ", lineup: 5, description: "恋愛運を占うコイン型グッズ", isNew: true, image: "images/034.jpg" },
  { id: 35, name: "まちぼうけGLAY", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "GLAYコラボまちぼうけシリーズ", isNew: true, image: "images/035.jpg" },
  { id: 36, name: "サンリオ リトルツインスターズ ぬいぐるみポシェット", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "キキララのぬいぐるみ型ポシェット", isNew: true, image: "images/036.jpg" },
  { id: 37, name: "ことりの葛まんじゅう うつろい", price: 200, releaseMonth: "2026-01", genre: "ミニチュア", maker: "SO-TA", lineup: 5, description: "葛まんじゅうモチーフのミニチュア", isNew: true, image: "images/037.jpg" },
  { id: 38, name: "EASTBOY ミニスクールバッグマスコット３", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "スクールバッグのミニチュアマスコット第3弾", isNew: true, image: "images/038.jpg" },
  { id: 39, name: "JILLbyJILLSTUART MINI FLUFFY TOTEBAG KEYHOLDER", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "JILLSTUART風ミニトートバッグ型キーホルダー", isNew: true, image: "images/039.jpg" },
  { id: 40, name: "ポムポムプリン マイカラーフィギュア", price: 300, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 6, description: "ポムポムプリンのカラフルフィギュア", isNew: true, image: "images/040.jpg" },
  { id: 41, name: "CoCo壱番屋 ミニチュアマスコットvol.2", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "CoCo壱メニューのミニチュアマスコット", isNew: true, image: "images/041.jpg" },
  { id: 42, name: "怒涛！チンチロマスコット2", price: 200, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "チンチロサイコロのマスコット第2弾", isNew: true, image: "images/042.jpg" },
  { id: 43, name: "サンリオ ポチャッコ ぬいぐるみボールチェーン", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポチャッコのぬいぐるみ型ボールチェーン", isNew: true, image: "images/043.jpg" },
  { id: 44, name: "野菜袋２", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "野菜パック袋のリアルミニチュア第2弾", isNew: true, image: "images/044.jpg" },
  { id: 45, name: "キン肉マン ドットフィギュアチャーム", price: 400, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 6, description: "キン肉マンのドット絵風フィギュアチャーム", isNew: true, image: "images/045.jpg" },
  { id: 46, name: "ヴィセ ミニチュアコレクション", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ヴィセコスメのミニチュアコレクション", isNew: true, image: "images/046.jpg" },
  { id: 47, name: "サンエックスユニバース バラエティーコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 6, description: "サンエックスキャラのバラエティーグッズ", isNew: true, image: "images/047.jpg" },
  { id: 48, name: "リラックマ のんびりネコ ふわふわポーチ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リラックマのふわふわポーチ", isNew: true, image: "images/048.jpg" },
  { id: 49, name: "はっぴ～ぬ！", price: 200, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "はっぴーな犬のマスコット", isNew: true, image: "images/049.jpg" },
  { id: 50, name: "ほっこり日和 猫", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫をモチーフにしたほっこりグッズ", isNew: true, image: "images/050.jpg" },
  { id: 51, name: "HG レジェンドライダーvol.5", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "仮面ライダーHGレジェンドライダー第5弾", isNew: true, image: "images/051.jpg" },
  { id: 52, name: "ちいかわ ライトクリップ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわのライト付きクリップ", isNew: true, image: "images/052.jpg" },
  { id: 53, name: "UNIVERSAL Music Push Button GODシリーズ", price: 500, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "音楽関連のプッシュボタン型グッズ", isNew: true, image: "images/053.jpg" },
  { id: 54, name: "ちいかわ×サンリオ なりきりフィギュア", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわがサンリオキャラに変身したフィギュア", isNew: true, image: "images/054.jpg" },
  { id: 55, name: "すみっコぐらし ほわっと光る！電球ライト2", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 6, description: "すみっコの電球型ライト第2弾", isNew: true, image: "images/055.jpg" },
  { id: 56, name: "リラックマ やわらかマスコット", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リラックマのやわらかマスコット", isNew: true, image: "images/056.jpg" },
  { id: 57, name: "モンチッチ もこもこスクエアポーチ くすみカラー", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "モンチッチのくすみカラーポーチ", isNew: true, image: "images/057.jpg" },
  { id: 58, name: "猫キャッチ", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫をキャッチするゲーム感覚グッズ", isNew: true, image: "images/058.jpg" },
  { id: 59, name: "ちいかわ×サンリオ レイヤーアクリルスタンド", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわ×サンリオのアクリルスタンド", isNew: true, image: "images/059.jpg" },
  { id: 60, name: "ないしょとーくFig. くまのプーさん", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "プーさんのないしょとーくフィギュア", isNew: true, image: "images/060.jpg" },
  { id: 61, name: "ハリー・ポッター ドビーいっぱいコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ハリポタのドビーコレクション", isNew: true, image: "images/061.jpg" },
  { id: 62, name: "サンリオキャラクターズ しっぽチャーム", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "サンリオキャラのしっぽ型チャーム", isNew: true, image: "images/062.jpg" },
  { id: 63, name: "なおにゃん スイング2", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "なおにゃんスイングマスコット第2弾", isNew: true, image: "images/063.jpg" },
  { id: 64, name: "HG ONE PIECE 01", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ワンピースHGフィギュア第1弾", isNew: true, image: "images/064.jpg" },
  { id: 65, name: "ミッフィー マスコットライトPart.3", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ミッフィーのライトマスコット第3弾", isNew: true, image: "images/065.jpg" },
  { id: 66, name: "リアル！呼び出しベル8", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "呼び出しベルをリアルに再現した第8弾", isNew: true, image: "images/066.jpg" },
  { id: 67, name: "サンリオ ステンドグラス風アクリルキーチェーン", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "ステンドグラス風サンリオキーチェーン", isNew: true, image: "images/067.jpg" },
  { id: 68, name: "リサとガスパール Fleurデザイン コレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リサガスのフルールデザインコレクション", isNew: true, image: "images/068.jpg" },
  { id: 69, name: "PINGU シリコンがまぐち", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ピングーのシリコン製がまぐち", isNew: true, image: "images/069.jpg" },
  { id: 70, name: "サンリオキャラクターズ お寿司キーチェーン", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのお寿司型キーチェーン", isNew: true, image: "images/070.jpg" },
  { id: 71, name: "タマ＆フレンズ BIG巾着&ポーチコレクション", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "タマ＆フレンズのBIG巾着とポーチ", isNew: true, image: "images/071.jpg" },
  { id: 72, name: "カードキャプターさくら くっつきマスコット", price: 500, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "CCさくらのくっつきマスコット", isNew: true, image: "images/072.jpg" },
  { id: 73, name: "機動戦士ガンダム ならぶんです。ザク", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ガンダムザクのならぶんですシリーズ", isNew: true, image: "images/073.jpg" },
  { id: 74, name: "POWER KNUCKLE byTOUMA × KAMEN RIDER", price: 1000, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 4, description: "仮面ライダーコラボフィギュア", isNew: true, image: "images/074.jpg" },
  { id: 75, name: "サンリオ カプセルステッキ2", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのステッキ第2弾", isNew: true, image: "images/075.jpg" },
  { id: 76, name: "豆ガシャ本 超全集 仮面ライダーシリーズ", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 5, description: "仮面ライダーシリーズの豆本超全集", isNew: true, image: "images/076.jpg" },
  { id: 77, name: "それいけ！アンパンマン ポップンハウス6", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "アンパンマンのポップンハウス第6弾", isNew: true, image: "images/077.jpg" },
  { id: 78, name: "MINECRAFT ならぶんです。7", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "マイクラのならぶんです第7弾", isNew: true, image: "images/078.jpg" },
  { id: 79, name: "銀魂 BIGソフビコレクション", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "銀魂のBIGサイズソフビフィギュア", isNew: true, image: "images/079.jpg" },
  { id: 80, name: "アンパンマン てころがしわくわくカー！4", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "アンパンマンの転がして遊べるカー第4弾", isNew: true, image: "images/080.jpg" },
  { id: 81, name: "まちぼうけ パンダの場合", price: 300, releaseMonth: "2026-01", genre: "動物", maker: "バンダイ", lineup: 5, description: "パンダのまちぼうけシリーズ", isNew: true, image: "images/081.jpg" },
  { id: 82, name: "ポケモン りらくっしょんマスコット party", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 6, description: "ポケモンのリラックスマスコット", isNew: true, image: "images/082.jpg" },
  { id: 83, name: "サンリオキャラクターズ Chocolate Doll", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 6, description: "サンリオキャラのチョコレートドール", isNew: true, image: "images/083.jpg" },
  { id: 84, name: "機動戦士ガンダム MOBILE SUIT ENSEMBLE 30", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ガンダムMSアンサンブル第30弾", isNew: true, image: "images/084.jpg" },
  { id: 85, name: "nepia ミニチュアチャーム", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ネピアティッシュのミニチュアチャーム", isNew: true, image: "images/085.jpg" },
  { id: 86, name: "タカセ洋菓子 ミニチュアチャーム", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "タカセ洋菓子のミニチュアチャーム", isNew: true, image: "images/086.jpg" },
  { id: 87, name: "MOOMIN もふもふポーシェット", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンのもふもふポーシェット", isNew: true, image: "images/087.jpg" },
  { id: 88, name: "サンリオ もふもふポーシェット2", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのもふもふポーシェット第2弾", isNew: true, image: "images/088.jpg" },
  { id: 89, name: "サンリオ きらっととんでいけしゃぼん玉", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのしゃぼん玉グッズ", isNew: true, image: "images/089.jpg" },
  { id: 90, name: "日清カップヌードル めじるしアクセサリー", price: 300, releaseMonth: "2026-01", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "カップヌードルのめじるしアクセサリー", isNew: true, image: "images/090.jpg" },
  { id: 91, name: "矢沢あい カプセルラバーマスコット", price: 300, releaseMonth: "2026-01", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "矢沢あい漫画キャラのラバーマスコット", isNew: true, image: "images/091.jpg" },
  { id: 92, name: "ソフビめじるしバンド サンリオ", price: 500, releaseMonth: "2026-01", genre: "推し活", maker: "バンダイ", lineup: 5, description: "サンリオのソフビ風めじるしバンド", isNew: true, image: "images/092.jpg" },
  { id: 93, name: "capsule flockies ハヌル×サンリオ", price: 400, releaseMonth: "2026-01", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "スタジオハヌルとサンリオのflockies", isNew: true, image: "images/093.jpg" },
  { id: 94, name: "たまごっち ブリスターパッケージコレクション", price: 400, releaseMonth: "2026-01", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "たまごっちパッケージのミニチュア", isNew: true, image: "images/094.jpg" },
  { id: 95, name: "赤ずきんチャチャ めじるしアクセサリー", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "赤ずきんチャチャのめじるしアクセサリー", isNew: true, image: "images/095.jpg" },
  { id: 96, name: "DOLLEL FIGURE COLLECTION3", price: 500, releaseMonth: "2026-01", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ドール型フィギュアコレクション第3弾", isNew: true, image: "images/096.jpg" },
  { id: 97, name: "妖怪手ぬぐい", price: 400, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "妖怪をモチーフにした手ぬぐい", isNew: true, image: "images/097.jpg" },
  { id: 98, name: "Kabuto ミニチュアヘルメットキーホルダー", price: 500, releaseMonth: "2026-01", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "カブトのミニチュアヘルメットキーホルダー", isNew: true, image: "images/098.jpg" },
  { id: 99, name: "縁起物和柄巾着", price: 300, releaseMonth: "2026-01", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "縁起物和柄の巾着袋", isNew: true, image: "images/099.jpg" },
  { id: 100, name: "緊急レバーマスコット5", price: 300, releaseMonth: "2026-01", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "緊急レバーモチーフのマスコット第5弾", isNew: true, image: "images/100.jpg" },
  { id: 101, name: "ぶらさがりハムスター", price: 400, releaseMonth: "2026-02", genre: "動物", maker: "タカラトミーアーツ", lineup: 5, description: "ぶら下がりハムスターのカプセルトイ", isNew: true, image: "images/101.jpg" },
  { id: 102, name: "ふくふくシマエナガ フロッキーソフビかふぇカラー", price: 300, releaseMonth: "2026-02", genre: "動物", maker: "アミューズ", lineup: 5, description: "シマエナガのフロッキーソフビ", isNew: true, image: "images/102.jpg" },
  { id: 103, name: "ころはむコロン ほおぶくろ巾着", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "アミューズ", lineup: 5, description: "ころはむコロンのほお袋型巾着", isNew: true, image: "images/103.jpg" },
  { id: 104, name: "オニすけ アクリルスタンドフィギュア", price: 300, releaseMonth: "2026-02", genre: "フィギュア", maker: "SO-TA", lineup: 5, description: "オニすけのアクリルスタンド", isNew: true, image: "images/104.jpg" },
  { id: 105, name: "ポケモン30周年 メタルチャームマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポケモン30周年記念メタルチャーム", isNew: true, image: "images/105.jpg" },
  { id: 106, name: "セサミストリート フラットポーチ", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "Qualia", lineup: 5, description: "セサミキャラのフラットポーチ", isNew: true, image: "images/106.jpg" },
  { id: 107, name: "ハローキティ 刺繍カスタムキーホルダー", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "ケーツーステーション", lineup: 5, description: "キティの刺繍キーホルダー", isNew: true, image: "images/107.jpg" },
  { id: 108, name: "アオハルスイング", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "コトフル", lineup: 5, description: "青春のスイングフィギュア", isNew: true, image: "images/108.jpg" },
  { id: 109, name: "サンリオ かおりつきフルーツ大福マスコット", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "ケーツーステーション", lineup: 5, description: "香り付きフルーツ大福型マスコット", isNew: true, image: "images/109.jpg" },
  { id: 110, name: "うちの子かわいい！ドッグリュック第2弾", price: 500, releaseMonth: "2026-02", genre: "動物", maker: "ピーナッツクラブ", lineup: 5, description: "犬型ミニリュック第2弾", isNew: true, image: "images/110.jpg" },
  { id: 111, name: "焼き芋袋2", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ターリン・インターナショナル", lineup: 5, description: "焼き芋袋のミニチュア", isNew: true, image: "images/111.jpg" },
  { id: 112, name: "いたずらぐまのグルーミー ネックストラップ", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "IP4", lineup: 5, description: "グルーミーのネックストラップ", isNew: true, image: "images/112.jpg" },
  { id: 113, name: "かわいい ぬいぐるみ BIG シャチ", price: 500, releaseMonth: "2026-02", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "大型シャチのぬいぐるみ", isNew: true, image: "images/113.jpg" },
  { id: 114, name: "柴犬根付３", price: 300, releaseMonth: "2026-02", genre: "動物", maker: "ターリン・インターナショナル", lineup: 5, description: "柴犬の根付コレクション第3弾", isNew: true, image: "images/114.jpg" },
  { id: 115, name: "きらめき☆バルーンフィギュア【推しの子】", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "【推しの子】のバルーンフィギュア", isNew: true, image: "images/115.jpg" },
  { id: 116, name: "ガンダムヘッド めじるしアクセサリー", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ガンダムヘッドのめじるしアクセサリー", isNew: true, image: "images/116.jpg" },
  { id: 117, name: "ワンピース ミニチュアチャーム", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "ONE PIECEウエハースのミニチュアチャーム", isNew: true, image: "images/117.jpg" },
  { id: 118, name: "ねこうさぎちゃん たれみみ", price: 400, releaseMonth: "2026-02", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "ねこうさぎのたれ耳ぬいぐるみ", isNew: true, image: "images/118.jpg" },
  { id: 119, name: "葬送のフリーレン つまんでつなげてますこっと2", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "フリーレンのマスコット第2弾", isNew: true, image: "images/119.jpg" },
  { id: 120, name: "でかリボンヘアクリップ", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "アミューズ", lineup: 5, description: "大きなリボンヘアクリップ", isNew: true, image: "images/120.jpg" },
  { id: 121, name: "うちの子のけだまだま", price: 400, releaseMonth: "2026-02", genre: "動物", maker: "ブライトリンク", lineup: 5, description: "けだまのマスコット", isNew: true, image: "images/121.jpg" },
  { id: 122, name: "mofusand×日比谷花壇 スカーフチャーム", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "パレード", lineup: 5, description: "mofusand×日比谷花壇コラボチャーム", isNew: true, image: "images/122.jpg" },
  { id: 123, name: "ONE PIECE ワンピの実ミクロ チャーム", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ONE PIECE悪魔の実ミニチュアチャーム", isNew: true, image: "images/123.jpg" },
  { id: 124, name: "みんなのポチャッコ これくしょん", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポチャッコのコレクション", isNew: true, image: "images/124.jpg" },
  { id: 125, name: "文房具刺繍チャーム", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "文房具モチーフの刺繍チャーム", isNew: true, image: "images/125.jpg" },
  { id: 126, name: "スーパーダンガンロンパ2 まちぼうけ", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ダンガンロンパ2まちぼうけ", isNew: true, image: "images/126.jpg" },
  { id: 127, name: "ダンボいっぱいコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニー・ダンボのマスコット", isNew: true, image: "images/127.jpg" },
  { id: 128, name: "着せ替え人形は恋をする Season2 キーホルダー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "着せ恋のラバーキーホルダー", isNew: true, image: "images/128.jpg" },
  { id: 129, name: "ポケモン トートバッグ＆ポーチvol.10", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ポケモンのミニトート＆ポーチ", isNew: true, image: "images/129.jpg" },
  { id: 130, name: "パンダの穴 ミニチュアスナイパー４", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "パンダの穴ミニチュア第4弾", isNew: true, image: "images/130.jpg" },
  { id: 131, name: "ミリオンゴッド BGMプッシュボタン", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "J.DREAM", lineup: 5, description: "ミリオンゴッドのBGM再生ボタン", isNew: true, image: "images/131.jpg" },
  { id: 132, name: "サンリオ がまぐちキーホルダー", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオのがまぐち型キーホルダー", isNew: true, image: "images/132.jpg" },
  { id: 133, name: "The History Collection PlayStation", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "プレステの歴史ミニチュア", isNew: true, image: "images/133.jpg" },
  { id: 134, name: "mofusand いちごチョコにゃんマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "mofusandいちごチョコのマスコット", isNew: true, image: "images/134.jpg" },
  { id: 135, name: "パンどろぼう カプセルヘアクリップ", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "パンどろぼうのヘアクリップ", isNew: true, image: "images/135.jpg" },
  { id: 136, name: "サンリオ ふわわフロッキーマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオのふわわフロッキーマスコット", isNew: true, image: "images/136.jpg" },
  { id: 137, name: "ケアベア クリアマスコットチャーム2", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "IP4", lineup: 5, description: "ケアベアのクリアチャーム第2弾", isNew: true, image: "images/137.jpg" },
  { id: 138, name: "ムーミン ぬいタオル", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "キタンクラブ", lineup: 5, description: "ムーミンのぬいぐるみタオル", isNew: true, image: "images/138.jpg" },
  { id: 139, name: "手のひらネットワーク機器4", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ターリン・インターナショナル", lineup: 5, description: "ネットワーク機器のミニチュア第4弾", isNew: true, image: "images/139.jpg" },
  { id: 140, name: "サンエックス 巾着＆ポーチコレクション", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "IP4", lineup: 5, description: "サンエックスの巾着＆ポーチ", isNew: true, image: "images/140.jpg" },
  { id: 141, name: "ティニピン バラエティーコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "IP4", lineup: 5, description: "ティニピンのバラエティーコレクション", isNew: true, image: "images/141.jpg" },
  { id: 142, name: "モンチッチ キーチェーンバッグコレクション", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "IP4", lineup: 5, description: "モンチッチのミニバッグコレクション", isNew: true, image: "images/142.jpg" },
  { id: 143, name: "ドラえもん Funny Time!", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ドラえもんのファニータイム", isNew: true, image: "images/143.jpg" },
  { id: 144, name: "けろけろけろっぴ バラエティーコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "IP4", lineup: 5, description: "けろっぴのバラエティーコレクション", isNew: true, image: "images/144.jpg" },
  { id: 145, name: "MINECRAFT めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "マイクラのめじるしアクセサリー", isNew: true, image: "images/145.jpg" },
  { id: 146, name: "パンツウエストポーチ", price: 400, releaseMonth: "2026-02", genre: "おもしろ", maker: "ターリン・インターナショナル", lineup: 5, description: "パンツ型ウエストポーチ", isNew: true, image: "images/146.jpg" },
  { id: 147, name: "Honda CIVIC TYPE R コレクション", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "IP4", lineup: 5, description: "ホンダシビックType Rミニカー", isNew: true, image: "images/147.jpg" },
  { id: 148, name: "Canon ミニチュアカメラコレクション", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "キヤノンカメラのミニチュア", isNew: true, image: "images/148.jpg" },
  { id: 149, name: "HGドラゴンボール04 MAJIN BUU SAGA", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ドラゴンボールHG魔人ブウ編", isNew: true, image: "images/149.jpg" },
  { id: 150, name: "パンダコパンダ 前髪クリップ2", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "IP4", lineup: 5, description: "パンダコパンダのヘアクリップ第2弾", isNew: true, image: "images/150.jpg" },
  { id: 151, name: "ELECTRO GAME COLLECTION 4", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "IP4", lineup: 5, description: "電子ゲーム機ミニチュア第4弾", isNew: true, image: "images/151.jpg" },
  { id: 152, name: "ミッフィー パステルバラエティーコレクション", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "IP4", lineup: 5, description: "ミッフィーのパステルコレクション", isNew: true, image: "images/152.jpg" },
  { id: 153, name: "Chiikawa Baby 巾着ポーチ", price: 500, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ちいかわベイビーの巾着ポーチ", isNew: true, image: "images/153.jpg" },
  { id: 154, name: "ドラクエVII ミニアクリルブロック", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "DQ7のミニアクリルブロック", isNew: true, image: "images/154.jpg" },
  { id: 155, name: "リサとガスパール ライトマスコット", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "リサガスのライトマスコット", isNew: true, image: "images/155.jpg" },
  { id: 156, name: "銀魂 吉原大炎上 めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "銀魂劇場版のめじるしアクセサリー", isNew: true, image: "images/156.jpg" },
  { id: 157, name: "HG スーパー戦隊シリーズ vol.2", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "スーパー戦隊HGフィギュア第2弾", isNew: true, image: "images/157.jpg" },
  { id: 158, name: "サンリオ カラフルカラビナチャーム", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオのカラビナチャーム", isNew: true, image: "images/158.jpg" },
  { id: 159, name: "クッピーラムネ めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "クッピーラムネのめじるし", isNew: true, image: "images/159.jpg" },
  { id: 160, name: "ペコちゃん めじるしアクセサリー2026", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "ペコちゃんお菓子のめじるし", isNew: true, image: "images/160.jpg" },
  { id: 161, name: "サンリオ GRWMマスコットチャーム", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオGRWM風マスコットチャーム", isNew: true, image: "images/161.jpg" },
  { id: 162, name: "クレヨンしんちゃん めざましサウンド", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "しんちゃんのめざましサウンド", isNew: true, image: "images/162.jpg" },
  { id: 163, name: "名探偵コナン コナン隊 プラス", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "コナン隊のフィギュアコレクション", isNew: true, image: "images/163.jpg" },
  { id: 164, name: "パワフルプロ野球 サウンドロップ", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "パワプロのサウンドドロップ", isNew: true, image: "images/164.jpg" },
  { id: 165, name: "ガンダム 閃光のハサウェイ ラバーマスコット", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "閃ハサのラバーマスコット", isNew: true, image: "images/165.jpg" },
  { id: 166, name: "まちぼうけ NARUTO ラーメン一楽 第2弾", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "NARUTOまちぼうけ第2弾", isNew: true, image: "images/166.jpg" },
  { id: 167, name: "ヒロアカ おくるみますこっとチャーム", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ヒロアカのおくるみマスコット", isNew: true, image: "images/167.jpg" },
  { id: 168, name: "kitson ミニチュアバッグコレクション", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "TOYS CABIN", lineup: 5, description: "kitsonのミニチュアバッグ", isNew: true, image: "images/168.jpg" },
  { id: 169, name: "暗闘で光る！UMA めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "暗闇で光るUMAのめじるし", isNew: true, image: "images/169.jpg" },
  { id: 170, name: "EVA POCKET めじるしアクセサリー", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "エヴァのポケットめじるし", isNew: true, image: "images/170.jpg" },
  { id: 171, name: "BASTARD!! カプセルフィギュア", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "BASTARD!!のカプセルフィギュア", isNew: true, image: "images/171.jpg" },
  { id: 172, name: "豆ガシャ本 サンリオ プロフィール帳", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "サンリオキャラのプロフィール帳", isNew: true, image: "images/172.jpg" },
  { id: 173, name: "アンパンマン カシャカシャ！みえるよ！", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "アンパンマンのカシャカシャおもちゃ", isNew: true, image: "images/173.jpg" },
  { id: 174, name: "TOM and JERRY おやつチャーム", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "トムジェリのしぼりクッキーチャーム", isNew: true, image: "images/174.jpg" },
  { id: 175, name: "パワーパフ ガールズ きゃらまかろん", price: 500, releaseMonth: "2026-02", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "パワパフガールズのフィギュア", isNew: true, image: "images/175.jpg" },
  { id: 176, name: "おしゅしだよ めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "おしゅしだよのめじるし", isNew: true, image: "images/176.jpg" },
  { id: 177, name: "どこでもいっしょ まちぼうけ２", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "どこいっしょまちぼうけ第2弾", isNew: true, image: "images/177.jpg" },
  { id: 178, name: "まちぼうけ キン肉マン2", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "キン肉マンまちぼうけ第2弾", isNew: true, image: "images/178.jpg" },
  { id: 179, name: "ディズニー Twinkle ゴム", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニーのキラキラゴムアクセ", isNew: true, image: "images/179.jpg" },
  { id: 180, name: "NEW ERA MLB Cap MINIATURE SWING", price: 500, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ターリン・インターナショナル", lineup: 5, description: "MLBキャップのミニチュアスイング", isNew: true, image: "images/180.jpg" },
  { id: 181, name: "おじゃる丸 めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "おじゃる丸のめじるし", isNew: true, image: "images/181.jpg" },
  { id: 182, name: "クレヨンしんちゃん ミニ貯金箱", price: 500, releaseMonth: "2026-02", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "しんちゃんのミニ貯金箱", isNew: true, image: "images/182.jpg" },
  { id: 183, name: "サムライ ミニチュアチャーム", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "サムライのミニチュアチャーム", isNew: true, image: "images/183.jpg" },
  { id: 184, name: "テレタビーズ おやすみライトマスコット", price: 500, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "テレタビーズのライトマスコット", isNew: true, image: "images/184.jpg" },
  { id: 185, name: "チロルチョコ めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "ミニチュア", maker: "ケンエレファント", lineup: 5, description: "チロルチョコのめじるし", isNew: true, image: "images/185.jpg" },
  { id: 186, name: "HUNTER×HUNTER すわらせ隊りある2", price: 800, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "H×Hすわらせフィギュア第2弾", isNew: true, image: "images/186.jpg" },
  { id: 187, name: "まちぼうけ 聖闘士星矢", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "聖闘士星矢まちぼうけ", isNew: true, image: "images/187.jpg" },
  { id: 188, name: "矢沢あい BIG METAL RING", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "J.DREAM", lineup: 5, description: "矢沢あいのビッグメタルリング", isNew: true, image: "images/188.jpg" },
  { id: 189, name: "トイ・ストーリー エイリアン だいすきフード", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トイストーリーエイリアンのフードマスコット", isNew: true, image: "images/189.jpg" },
  { id: 190, name: "魔法使いサリー ミニチュアチャーム", price: 400, releaseMonth: "2026-02", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "魔法使いサリーのミニチュア", isNew: true, image: "images/190.jpg" },
  { id: 191, name: "パペットスンスン コインケース", price: 400, releaseMonth: "2026-02", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "スンスンのコインケース", isNew: true, image: "images/191.jpg" },
  { id: 192, name: "よつばと！ こまどりフィギュア", price: 400, releaseMonth: "2026-02", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "よつばと！のこまどりフィギュア", isNew: true, image: "images/192.jpg" },
  { id: 193, name: "ホイッピ＆ラッピ アクリルチャーム", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ホイッピ＆ラッピのアクリルチャーム", isNew: true, image: "images/193.jpg" },
  { id: 194, name: "MUZIKTIGER ヘアアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "IP4", lineup: 5, description: "MUZIKTIGERのヘアアクセサリー", isNew: true, image: "images/194.jpg" },
  { id: 195, name: "San-X フィギュアコレクション Vol.2", price: 300, releaseMonth: "2026-02", genre: "フィギュア", maker: "エスケイジャパン", lineup: 5, description: "サンエックスオールスターズフィギュア", isNew: true, image: "images/195.jpg" },
  { id: 196, name: "まちぼうけ ウルトラマンの場合", price: 400, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ウルトラマンまちぼうけ", isNew: true, image: "images/196.jpg" },
  { id: 197, name: "クレヨンしんちゃん ミラーコレクション", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "しんちゃんのミラーコレクション", isNew: true, image: "images/197.jpg" },
  { id: 198, name: "幽☆遊☆白書 めじるしアクセサリー", price: 300, releaseMonth: "2026-02", genre: "推し活", maker: "バンダイ", lineup: 5, description: "幽遊白書のめじるし", isNew: true, image: "images/198.jpg" },
  { id: 199, name: "コジコジ スイング", price: 300, releaseMonth: "2026-02", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "コジコジのスイングフィギュア", isNew: true, image: "images/199.jpg" },

  { id: 201, name: "はぴだんぶい キラキラも～っと☆おうえんフィギュア", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "はぴだんぶいの応援フィギュア", isNew: true, image: "images/201.jpg" },
  { id: 202, name: "推し×スシ 推スシ", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "タカラトミーアーツ", lineup: 5, description: "推し活×寿司のコラボネタマスコット", isNew: true, image: "images/202.jpg" },
  { id: 203, name: "こっちむいてFig.その着せ替え人形は恋をする", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "その着せ替え人形は恋をするの着せ替えフィギュア", isNew: true, image: "images/203.jpg" },
  { id: 204, name: "MOOMINフロッキーフィギュアマスコット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンのふわふわフロッキーマスコット", isNew: true, image: "images/204.jpg" },
  { id: 205, name: "miffy すやすやフレンドFig.ぱすてる", price: 200, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ミッフィーのパステルカラーフィギュア", isNew: true, image: "images/205.jpg" },
  { id: 206, name: "カプセルプラレール きかんしゃトーマス", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "トーマスのカプセルプラレール", isNew: true, image: "images/206.jpg" },
  { id: 207, name: "SANKYO激熱柄・激熱音プッシュボタンマスコット", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "J.DREAM", lineup: 5, description: "パチンコの激熱柄＆音が楽しめるプッシュボタンマスコット", isNew: true, image: "images/207.jpg" },
  { id: 208, name: "ぷよぷよ マスコットめじるしチャーム", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "ピーナッツクラブ", lineup: 5, description: "ぷよぷよキャラのめじるしチャーム", isNew: true, image: "images/208.jpg" },
  { id: 209, name: "ちいかわ ラメアクリルキーホルダー5", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "パレード", lineup: 5, description: "ちいかわのラメ入りアクリルキーホルダー", isNew: true, image: "images/209.jpg" },
  { id: 210, name: "CONVERSE SHOES COLLECTION めじるしアクセサリー", price: 400, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "コンバーススニーカーのミニチュアアクセサリー", isNew: true, image: "images/210.jpg" },
  { id: 211, name: "どっちも主役！ポメラニアン", price: 200, releaseMonth: "2026-03", genre: "動物", maker: "エール", lineup: 5, description: "ポメラニアンのキュートなマスコット", isNew: true, image: "images/211.jpg" },
  { id: 212, name: "チュッパチャプス ミニチュアコレクション Limited flavor2", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "チュッパチャプスの限定フレーバーミニチュア", isNew: true, image: "images/212.jpg" },
  { id: 213, name: "ホビーガチャ トヨタ GR Supra -COMPLATE EDITION-", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "トヨタGRスープラの完成品ミニカー", isNew: true, image: "images/213.jpg" },
  { id: 214, name: "どこでもいっしょ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "バンダイ", lineup: 5, description: "トロのめじるしアクセサリー", isNew: true, image: "images/214.jpg" },
  { id: 215, name: "本当に剥けちゃう！むにゅむにゅ！ふつ〜のバナナマスコット", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "トイズスピリッツ", lineup: 5, description: "皮が剥けるリアルなバナナマスコット", isNew: true, image: "images/215.jpg" },
  { id: 216, name: "ギャビーのドールハウス ザ・ムービー つながるラバーマスコット", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ギャビーのドールハウスキャラのつながるラバーマスコット", isNew: true, image: "images/216.jpg" },
  { id: 217, name: "EVERLAST ボクシンググローブコレクション", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "エバーラストのボクシンググローブミニチュア", isNew: true, image: "images/217.jpg" },
  { id: 218, name: "ミッフィー巾着コレクション", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "IP4", lineup: 5, description: "ミッフィー柄の巾着バッグコレクション", isNew: true, image: "images/218.jpg" },
  { id: 219, name: "しなこ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "バンダイ", lineup: 5, description: "しなこのめじるしアクセサリー", isNew: true, image: "images/219.jpg" },
  { id: 220, name: "ヤマザキパン ミニチュアチャーム2", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "ヤマザキパンのミニチュアチャーム", isNew: true, image: "images/220.jpg" },
  { id: 221, name: "ミートバッグ", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "トーシン", lineup: 5, description: "お肉のバッグ型ユニークグッズ", isNew: true, image: "images/221.jpg" },
  { id: 222, name: "ふんばり～ぬ3", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "ふんばる犬のユニークマスコット第3弾", isNew: true, image: "images/222.jpg" },
  { id: 223, name: "BRANDALISEDアクリルキーチェーン", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "コトフル", lineup: 5, description: "ブランド商品のアクリルキーチェーン", isNew: true, image: "images/223.jpg" },
  { id: 224, name: "パウ・パトロール パウっとつながるマスコット2", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "パウパトロールのつながるマスコット第2弾", isNew: true, image: "images/224.jpg" },
  { id: 225, name: "B.LEAGUE マスコット めじるしアクセサリー2", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "Bリーグ各チームマスコットのめじるしアクセサリー", isNew: true, image: "images/225.jpg" },
  { id: 226, name: "運命のコイン4", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "ブシロードクリエイティブ", lineup: 5, description: "運命を占うコインコレクション第4弾", isNew: true, image: "images/226.jpg" },
  { id: 227, name: "Calbeeじゃがりこ おみくじマスコット", price: 500, releaseMonth: "2026-03", genre: "ミニチュア", maker: "ウルトラニュープランニング", lineup: 5, description: "じゃがりこパッケージのおみくじマスコット", isNew: true, image: "images/227.jpg" },
  { id: 228, name: "ズートピア ブリスターチャームコレクション", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ズートピアキャラのブリスターチャーム", isNew: true, image: "images/228.jpg" },
  { id: 229, name: "トゥイーティーなりきりスイング", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "トゥイーティーのきぐるみスイングマスコット", isNew: true, image: "images/229.jpg" },
  { id: 230, name: "AIP森口修の猫フィギュアマスコット3", price: 500, releaseMonth: "2026-03", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "森口修デザインの猫フィギュアマスコット", isNew: true, image: "images/230.jpg" },
  { id: 231, name: "コジコジ Capsule Flockies", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "コジコジのcapsule flockies", isNew: true, image: "images/231.jpg" },
  { id: 232, name: "機動戦士ガンダム ならぶんです。ハロ ビッグサイズ", price: 800, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ガンダムのハロが並ぶビッグサイズフィギュア", isNew: true, image: "images/232.jpg" },
  { id: 233, name: "MOOMIN マスコットチャーム～funny style～", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ムーミンの面白いスタイルのマスコットチャーム", isNew: true, image: "images/233.jpg" },
  { id: 234, name: "MINECRAFT ライトマスコット3", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "マインクラフトの光るライトマスコット第3弾", isNew: true, image: "images/234.jpg" },
  { id: 235, name: "capsule flockies Winnie the Pooh", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "くまのプーさんのcapsule flockies", isNew: true, image: "images/235.jpg" },
  { id: 236, name: "PEANUTS パッケージミニチュアコレクション クラシックver.", price: 400, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "スヌーピーパッケージのミニチュアコレクション", isNew: true, image: "images/236.jpg" },
  { id: 237, name: "From TV animation ONE PIECE ワンピの実 GRAND CAPSULE Vol.02", price: 1500, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ONE PIECE悪魔の実のグランドカプセル第2弾", isNew: true, image: "images/237.jpg" },
  { id: 238, name: "ウルトラマン MINI ULTRA ART めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ウルトラマンのミニウルトラアートめじるしアクセサリー", isNew: true, image: "images/238.jpg" },
  { id: 239, name: "プロ野球マスコット めじるしアクセサリー", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "プロ野球各球団マスコットのめじるしアクセサリー", isNew: true, image: "images/239.jpg" },
  { id: 240, name: "ポケットモンスター 旅立ちの3匹アクリルスイング", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "旅立ちの3匹のアクリルスイングチャーム", isNew: true, image: "images/240.jpg" },
  { id: 241, name: "PEANUTS ビスケットミニチュアチャーム", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "スヌーピー柄ビスケットのミニチュアチャーム", isNew: true, image: "images/241.jpg" },
  { id: 242, name: "サンリオキャラクターズ シュウマイ", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのシュウマイ型マスコット", isNew: true, image: "images/242.jpg" },
  { id: 243, name: "映画ドラえもん メモリアルウォータードームコレクション", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "映画ドラえもんの水中ドーム型コレクション", isNew: true, image: "images/243.jpg" },
  { id: 244, name: "妖怪ウォッチ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "妖怪ウォッチキャラのめじるしアクセサリー", isNew: true, image: "images/244.jpg" },
  { id: 245, name: "パンダの穴 PET HOOD", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "タカラトミーアーツ", lineup: 5, description: "パンダの穴のペット用フード", isNew: true, image: "images/245.jpg" },
  { id: 246, name: "内藤ルネ ルネパンダ アクリルめじるしチャーム", price: 300, releaseMonth: "2026-03", genre: "動物", maker: "ピーナッツクラブ", lineup: 5, description: "内藤ルネのルネパンダアクリルチャーム", isNew: true, image: "images/246.jpg" },
  { id: 247, name: "モンチッチ めじるしアクセサリー2", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "モンチッチのめじるしアクセサリー第2弾", isNew: true, image: "images/247.jpg" },
  { id: 248, name: "Studio Haneul×Sanrio characters ふわふわフロッキーマスコット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "Qualia", lineup: 5, description: "スタジオハヌール×サンリオのふわふわフロッキー", isNew: true, image: "images/248.jpg" },
  { id: 249, name: "ジョジョの奇妙な冒険 まちぼうけ スターダストクルセイダース01", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ジョジョ第三部のまちぼうけフィギュア", isNew: true, image: "images/249.jpg" },
  { id: 250, name: "＠CTION RIDE 仮面ライダー5", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "仮面ライダーのアクションライドフィギュア第5弾", isNew: true, image: "images/250.jpg" },
  { id: 251, name: "レトロメモリーズうわばき入れ風カードポーチ", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "アミューズ", lineup: 5, description: "懐かしいうわばき入れデザインのカードポーチ", isNew: true, image: "images/251.jpg" },
  { id: 252, name: "パワーパフガールズ きぐるみスイング", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "パワーパフガールズのきぐるみスイングマスコット", isNew: true, image: "images/252.jpg" },
  { id: 253, name: "ポケモン30周年 メタルチャームマスコット", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポケモン30周年記念メタルチャーム", isNew: true, image: "images/253.jpg" },
  { id: 254, name: "機動戦士ガンダム ガシャポン戦士ZERO 01", price: 300, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "ガンダムガシャポン戦士ZEROシリーズ", isNew: true, image: "images/254.jpg" },
  { id: 255, name: "葬送のフリーレン ねむらせ隊", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "葬送のフリーレンのねむらせ隊フィギュア", isNew: true, image: "images/255.jpg" },
  { id: 256, name: "ドラえもん つながリングチャーム", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ドラえもんのつながるリングチャーム", isNew: true, image: "images/256.jpg" },
  { id: 257, name: "capsule flockies たまごっち", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "たまごっちのcapsule flockies", isNew: true, image: "images/257.jpg" },
  { id: 258, name: "光るポメラニアン", price: 500, releaseMonth: "2026-03", genre: "動物", maker: "ブシロードクリエイティブ", lineup: 5, description: "光るポメラニアンマスコット", isNew: true, image: "images/258.jpg" },
  { id: 259, name: "3年Z組銀八先生 まちぼうけ", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "銀八先生のまちぼうけフィギュア", isNew: true, image: "images/259.jpg" },
  { id: 260, name: "キン肉マン ダイキャストキンケシ12", price: 500, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "キン肉マンのダイキャストキンケシ第12弾", isNew: true, image: "images/260.jpg" },
  { id: 261, name: "名探偵コナン めじるしアクセサリー3", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "バンダイ", lineup: 5, description: "名探偵コナンのめじるしアクセサリー第3弾", isNew: true, image: "images/261.jpg" },
  { id: 262, name: "ちびまる子ちゃん ぬいぐるみ巾着3", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "夢屋", lineup: 5, description: "ちびまる子ちゃんのぬいぐるみ巾着第3弾", isNew: true, image: "images/262.jpg" },
  { id: 263, name: "東京メトロ サウンドロップ", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "東京メトロの音が鳴るサウンドロップ", isNew: true, image: "images/263.jpg" },
  { id: 264, name: "サンリオキャラクターズ ミニチャーム付きリボンタッセルPart.2", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "IP4", lineup: 5, description: "サンリオキャラのリボンタッセル第2弾", isNew: true, image: "images/264.jpg" },
  { id: 265, name: "ふくふくシマエナガ 文庫本用巾着トート", price: 400, releaseMonth: "2026-03", genre: "動物", maker: "アミューズ", lineup: 5, description: "シマエナガ柄の文庫本用巾着トート", isNew: true, image: "images/265.jpg" },
  { id: 266, name: "サンリオキャラクターズ ワンダフルワールドバッグコレクション", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "IP4", lineup: 5, description: "サンリオのワンダフルワールドバッグ", isNew: true, image: "images/266.jpg" },
  { id: 267, name: "DARTSLIVE サウンドミニチュアコレクション2", price: 500, releaseMonth: "2026-03", genre: "ミニチュア", maker: "バンダイ", lineup: 5, description: "ダーツのサウンドミニチュア第2弾", isNew: true, image: "images/267.jpg" },
  { id: 268, name: "つくし坊や はさむんです。でらっくす", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "バンダイ", lineup: 5, description: "つくし坊やのはさむクリップでらっくす", isNew: true, image: "images/268.jpg" },
  { id: 269, name: "サンリオキャラクターズ いつも一緒フレームキーチェーン Part.1", price: 300, releaseMonth: "2026-03", genre: "推し活", maker: "IP4", lineup: 5, description: "サンリオキャラのフレームキーチェーン", isNew: true, image: "images/269.jpg" },
  { id: 270, name: "ダッシュ無用！ピンポン PREMIUM2", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "IP4", lineup: 5, description: "ピンポン球のプレミアムマスコット第2弾", isNew: true, image: "images/270.jpg" },
  { id: 271, name: "サンリオキャラクターズ クッキー缶チャーム", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオキャラのクッキー缶型チャーム", isNew: true, image: "images/271.jpg" },
  { id: 272, name: "まちぼうけ ドラゴンボール3", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ドラゴンボールのまちぼうけフィギュア第3弾", isNew: true, image: "images/272.jpg" },
  { id: 273, name: "ハローキティ めじるしアクセサリー", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ハローキティのめじるしアクセサリー", isNew: true, image: "images/273.jpg" },
  { id: 274, name: "毛玉ビーム", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "ケンエレファント", lineup: 5, description: "猫の毛玉ビーム発射ユニークグッズ", isNew: true, image: "images/274.jpg" },
  { id: 275, name: "すみっコぐらし 喫茶すみっコでいちごフェア マスコットライト2", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "IP4", lineup: 5, description: "すみっコぐらしのマスコットライト第2弾", isNew: true, image: "images/275.jpg" },
  { id: 276, name: "サンリオ ハンギョドン ぬいぐるみボールチェーン2", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "夢屋", lineup: 5, description: "ハンギョドンのぬいぐるみボールチェーン", isNew: true, image: "images/276.jpg" },
  { id: 277, name: "ピクサーキャラクター ファッションリング ロイヤルクリア", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ピクサーキャラのファッションリング", isNew: true, image: "images/277.jpg" },
  { id: 278, name: "戦車のタンコ", price: 400, releaseMonth: "2026-03", genre: "おもしろ", maker: "TOYS CABIN", lineup: 5, description: "戦車のタンコキャラクターグッズ", isNew: true, image: "images/278.jpg" },
  { id: 279, name: "東京ばな奈 スクイーズマスコット", price: 300, releaseMonth: "2026-03", genre: "ミニチュア", maker: "タカラトミーアーツ", lineup: 5, description: "東京ばな奈のスクイーズマスコット", isNew: true, image: "images/279.jpg" },
  { id: 280, name: "San-Xオールスターズ BOXティッシュカバー", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "IP4", lineup: 5, description: "サンエックスキャラのティッシュボックスカバー", isNew: true, image: "images/280.jpg" },
  { id: 281, name: "肩ズンFig. MOOMIN Part4", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ムーミンの肩乗りフィギュア第4弾", isNew: true, image: "images/281.jpg" },
  { id: 282, name: "PEANUTS もふもふポーシェット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "スヌーピーのもふもふポーチ", isNew: true, image: "images/282.jpg" },
  { id: 283, name: "マイメロディ ぬいぐるみチャーム", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "夢屋", lineup: 5, description: "マイメロディのぬいぐるみチャーム", isNew: true, image: "images/283.jpg" },
  { id: 284, name: "転生したらスライムだった件 リムルさまがいっぱいフィギュア", price: 300, releaseMonth: "2026-03", genre: "フィギュア", maker: "バンダイ", lineup: 5, description: "転スラのリムルさまフィギュア", isNew: true, image: "images/284.jpg" },
  { id: 285, name: "サンリオ ウサハナ ぬいぐるみポシェット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "夢屋", lineup: 5, description: "ウサハナのぬいぐるみポーチ", isNew: true, image: "images/285.jpg" },
  { id: 286, name: "ドラネッツ3飛竜型", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "TOYS CABIN", lineup: 5, description: "ドラネッツの飛竜型フィギュア", isNew: true, image: "images/286.jpg" },
  { id: 287, name: "サンリオ ハローキティ トートバッグ", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "夢屋", lineup: 5, description: "ハローキティのトートバッグ", isNew: true, image: "images/287.jpg" },
  { id: 288, name: "うちのポケモンマスコット しらんぷり", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "うちのポケモンのしらんぷりマスコット", isNew: true, image: "images/288.jpg" },
  { id: 289, name: "サンリオキャラクターズ おきあがりマスコット4", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "夢屋", lineup: 5, description: "サンリオキャラのおきあがりこぼし第4弾", isNew: true, image: "images/289.jpg" },
  { id: 290, name: "ポップンユニコーンぷちぐるみ", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "アミューズ", lineup: 5, description: "ポップンユニコーンのぷちぬいぐるみ", isNew: true, image: "images/290.jpg" },
  { id: 291, name: "メダリスト スピンアクリルスタンド", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "TOYS CABIN", lineup: 5, description: "メダリストのスピンアクリルスタンド", isNew: true, image: "images/291.jpg" },
  { id: 292, name: "ディズニープリンセス まみれるFig.", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニープリンセスのまみれるフィギュア", isNew: true, image: "images/292.jpg" },
  { id: 293, name: "初音ミク すってんころりんフィギュア2", price: 400, releaseMonth: "2026-03", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "初音ミクの転倒フィギュア第2弾", isNew: true, image: "images/293.jpg" },
  { id: 294, name: "おそ松さん ぺたっとねじまきますこっと", price: 500, releaseMonth: "2026-03", genre: "キャラクター", maker: "ブシロードクリエイティブ", lineup: 5, description: "おそ松さんのネジマスコット", isNew: true, image: "images/294.jpg" },
  { id: 295, name: "ハローキティ 喜怒★哀楽!?ファションリングコレクション", price: 300, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "キティの喜怒哀楽ファッションリング", isNew: true, image: "images/295.jpg" },
  { id: 296, name: "カーラーついてますよ。ヘアクリップ", price: 500, releaseMonth: "2026-03", genre: "おもしろ", maker: "ブシロードクリエイティブ", lineup: 5, description: "カーラー付きのヘアクリップ", isNew: true, image: "images/296.jpg" },
  { id: 297, name: "サモエドくん ふわふわぽん", price: 300, releaseMonth: "2026-03", genre: "動物", maker: "アミューズ", lineup: 5, description: "サモエドくんのふわふわマスコット", isNew: true, image: "images/297.jpg" },
  { id: 298, name: "ずりおちピンチ！にゃんこフック", price: 300, releaseMonth: "2026-03", genre: "おもしろ", maker: "ブライトリンク", lineup: 5, description: "滑り落ち防止のにゃんこフック", isNew: true, image: "images/298.jpg" },
  { id: 299, name: "サンリオキャラクターズ さくらマジックアクリルカラビナ", price: 400, releaseMonth: "2026-03", genre: "推し活", maker: "IP4", lineup: 5, description: "サンリオキャラの桜マジックアクリルカラビナ", isNew: true, image: "images/299.jpg" },
  { id: 300, name: "サンリオキャラクターズ ふわふわパンマスコット", price: 400, releaseMonth: "2026-03", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "サンリオキャラのふわふわパンマスコット", isNew: true, image: "images/300.jpg" },
  { id: 301, name: "ポケモン ぽかぽかびより2", price: 400, releaseMonth: "2026-04", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポケモンのぽかぽかびより第2弾", isNew: true, image: "images/301.jpg" },
  { id: 302, name: "ポケモン フニットマスコット7", price: 300, releaseMonth: "2026-04", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ポケモンのフニットマスコット第7弾", isNew: true, image: "images/302.jpg" },
  { id: 303, name: "ホロライブ すわらせ隊 アクリルスタンド カラーライズ1", price: 400, releaseMonth: "2026-04", genre: "推し活", maker: "バンダイ", lineup: 5, description: "ホロライブすわらせ隊のアクリルスタンド", isNew: true, image: "images/303.jpg" },
  { id: 304, name: "ふわねこのmineチャーム", price: 400, releaseMonth: "2026-04", genre: "動物", maker: "J.DREAM", lineup: 5, description: "ふわねこのマインクラフトチャーム", isNew: true, image: "images/304.jpg" },
  { id: 305, name: "ゴリランドセル おんなのこバージョン マスコットフィギュア3", price: 500, releaseMonth: "2026-04", genre: "フィギュア", maker: "J.DREAM", lineup: 5, description: "ゴリランドセルの女子向けマスコット第3弾", isNew: true, image: "images/305.jpg" },
  { id: 306, name: "ATC 戦国のぼりコレクション 天下統一編", price: 400, releaseMonth: "2026-04", genre: "おもしろ", maker: "いきもん", lineup: 8, description: "戦国武将のぼりコレクション", isNew: true, image: "images/306.jpg" },
  { id: 307, name: "ムーミン きりかぶの時計", price: 500, releaseMonth: "2026-04", genre: "キャラクター", maker: "キタンクラブ", lineup: 5, description: "ムーミンのきりかぶ型時計", isNew: true, image: "images/307.jpg" },
  { id: 308, name: "ハイキュー!! ミニカチューシャマスコット", price: 500, releaseMonth: "2026-04", genre: "キャラクター", maker: "ケーツーステーション", lineup: 5, description: "ハイキュー!!のカチューシャマスコット", isNew: true, image: "images/308.jpg" },
  { id: 309, name: "ちびまる子ちゃん ヘアバンド", price: 400, releaseMonth: "2026-04", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ちびまる子ちゃんのヘアバンド", isNew: true, image: "images/309.jpg" },
  { id: 310, name: "ラッコのあかちゃん ぬいぐるみ", price: 300, releaseMonth: "2026-04", genre: "動物", maker: "キタンクラブ", lineup: 6, description: "ラッコの赤ちゃんぬいぐるみ", isNew: true, image: "images/310.jpg" },
  { id: 311, name: "満月珈琲店ミニチュア 世界を巡る満月珈琲店", price: 500, releaseMonth: "2026-04", genre: "ミニチュア", maker: "J.DREAM", lineup: 5, description: "満月珈琲店のミニチュアコレクション", isNew: true, image: "images/311.jpg" },
  { id: 312, name: "ねこのぬいぐるみ フロッキーマスコット", price: 400, releaseMonth: "2026-04", genre: "動物", maker: "J.DREAM", lineup: 5, description: "猫のぬいぐるみフロッキーマスコット", isNew: true, image: "images/312.jpg" },
  { id: 313, name: "箱入り野菜マスコット5", price: 400, releaseMonth: "2026-04", genre: "ミニチュア", maker: "J.DREAM", lineup: 5, description: "野菜パックのミニチュアマスコット第5弾", isNew: true, image: "images/313.jpg" },
  { id: 314, name: "ぷにっと！お刺身パック", price: 400, releaseMonth: "2026-04", genre: "ミニチュア", maker: "J.DREAM", lineup: 5, description: "お刺身パックのぷにぷにマスコット", isNew: true, image: "images/314.jpg" },
  { id: 315, name: "つながリングチャーム 劇場版チェンソーマン ポチタ", price: 300, releaseMonth: "2026-04", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "チェンソーマンポチタのリングチャーム", isNew: true, image: "images/315.jpg" },
  { id: 316, name: "にこにこぷん めじるしガチャマスコット", price: 500, releaseMonth: "2026-04", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "にこにこぷんのめじるしマスコット", isNew: true, image: "images/316.jpg" },
  { id: 317, name: "『テイルズ オブ』シリーズ30周年 ミニチュアパッケージチャーム", price: 400, releaseMonth: "2026-05", genre: "キャラクター", maker: "ピーナッツクラブ", lineup: 5, description: "テイルズシリーズ30周年パッケージチャーム", isNew: true, image: "images/317.jpg" },
  { id: 318, name: "ホロライブ おなまえぷっくりラバーマスコット1", price: 400, releaseMonth: "2026-05", genre: "推し活", maker: "ウルトラニュープランニング", lineup: 6, description: "ホロライブの名前入りラバーマスコット", isNew: true, image: "images/318.jpg" },
  { id: 319, name: "僕のヒーローアカデミア みあげてすたぁ カプセルラバーキーホルダー", price: 300, releaseMonth: "2026-05", genre: "キャラクター", maker: "TOYS CABIN", lineup: 7, description: "ヒロアカのラバーキーホルダー", isNew: true, image: "images/319.jpg" },
  { id: 320, name: "ドムドムハンバーガー ふわふわポーチ", price: 400, releaseMonth: "2026-05", genre: "ミニチュア", maker: "ディーアイエス", lineup: 5, description: "ドムドムハンバーガーのふわふわポーチ", isNew: true, image: "images/320.jpg" },
  { id: 321, name: "PiTaPaカード＆決済端末2", price: 400, releaseMonth: "2026-05", genre: "おもしろ", maker: "ディーアイエス", lineup: 5, description: "PiTaPaのミニチュアマスコット第2弾", isNew: true, image: "images/321.jpg" },
  { id: 322, name: "おジャ魔女どれみ ダイキャストチャーム＆パッケージ", price: 500, releaseMonth: "2026-05", genre: "キャラクター", maker: "TOYS CABIN", lineup: 4, description: "おジャ魔女どれみのダイキャストチャーム", isNew: true, image: "images/322.jpg" },
  { id: 323, name: "リラックマ コインケース", price: 300, releaseMonth: "2026-05", genre: "キャラクター", maker: "IP4", lineup: 5, description: "リラックマのコインケース", isNew: true, image: "images/323.jpg" },
  { id: 324, name: "つぶねこさま", price: 500, releaseMonth: "2026-05", genre: "動物", maker: "レインボー", lineup: 4, description: "つぶねこさまのマスコット", isNew: true, image: "images/324.jpg" },
  { id: 325, name: "侍ジャパン×サンリオキャラクターズ ぬいぐるみばっじvol.2", price: 500, releaseMonth: "2026-05", genre: "推し活", maker: "ブシロードクリエイティブ", lineup: 5, description: "侍ジャパン×サンリオのぬいぐるみバッジ", isNew: true, image: "images/325.jpg" },
  { id: 326, name: "BEN THE SPOOKY CAT3", price: 400, releaseMonth: "2026-05", genre: "動物", maker: "SO-TA", lineup: 10, description: "BEN THE SPOOKY CAT第3弾", isNew: true, image: "images/326.jpg" },
  { id: 327, name: "1/1 ヘラクレスオオカブト ver2.0", price: 500, releaseMonth: "2026-05", genre: "フィギュア", maker: "SO-TA", lineup: 3, description: "ヘラクレスオオカブト実物大フィギュア", isNew: true, image: "images/327.jpg" },
  { id: 328, name: "ぷよぷよ シャカシャカアクリルキーチェーン", price: 400, releaseMonth: "2026-05", genre: "キャラクター", maker: "ブシロード", lineup: 5, description: "ぷよぷよのシャカシャカアクリルキーチェーン", isNew: true, image: "images/328.jpg" },
  { id: 329, name: "刀剣乱舞 ONLINE 景趣フラットポーチ", price: 500, releaseMonth: "2026-05", genre: "推し活", maker: "ブシロード", lineup: 5, description: "刀剣乱舞の景趣フラットポーチ", isNew: true, image: "images/329.jpg" },
  { id: 330, name: "猫のバブーシュカ ネコーシュカ", price: 500, releaseMonth: "2026-06", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "猫のバブーシュカ型マスコット", isNew: true, image: "images/330.jpg" },
  { id: 331, name: "THUMB CAT サムキャット", price: 400, releaseMonth: "2026-06", genre: "動物", maker: "キタンクラブ", lineup: 5, description: "親指猫のマスコット", isNew: true, image: "images/331.jpg" },
  { id: 332, name: "アートインザポケット ムーミン Vol.6", price: 500, releaseMonth: "2026-06", genre: "キャラクター", maker: "キタンクラブ", lineup: 5, description: "ムーミンのアートインザポケット第6弾", isNew: true, image: "images/332.jpg" },
  { id: 333, name: "サンリオキャラクターズ ダンボールウォッチ3", price: 500, releaseMonth: "2026-06", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "サンリオのダンボールウォッチ第3弾", isNew: true, image: "images/333.jpg" },
  { id: 334, name: "DEATH NOTE コレクションフィギュアRICH", price: 500, releaseMonth: "2026-06", genre: "フィギュア", maker: "タカラトミーアーツ", lineup: 5, description: "DEATH NOTEのフィギュア", isNew: true, image: "images/334.jpg" },
  { id: 335, name: "にこにこぷん フィンガーパペット", price: 500, releaseMonth: "2026-06", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "にこにこぷんのフィンガーパペット", isNew: true, image: "images/335.jpg" },
  { id: 336, name: "機動戦士ガンダム まちぼうけ ノーマルスーツの場合", price: 400, releaseMonth: "2026-06", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ガンダムのまちぼうけノーマルスーツ", isNew: true, image: "images/336.jpg" },
  { id: 337, name: "ディズニーキャラクター Pretty Face ポーチ", price: 400, releaseMonth: "2026-06", genre: "キャラクター", maker: "タカラトミーアーツ", lineup: 5, description: "ディズニーのプリティフェイスポーチ", isNew: true, image: "images/337.jpg" },
  { id: 338, name: "ポケモン もふもふポーシェット", price: 400, releaseMonth: "2026-06", genre: "キャラクター", maker: "バンダイ", lineup: 5, description: "ポケモンのもふもふポーシェット", isNew: true, image: "images/338.jpg" }

];
